### ISSUE TITLE
【Angular2开发指南】6. 依赖注入

### ISSUE THREAD

**Issue by liangjingzhan** [gf-rd/blog#12]
## 依赖注入

> Angular的依赖注入会在适当的时候创建和注入所依赖的服务。

依赖注入（DI）是一个重要的应用设计模式。Angular有自己的DI框架，创建Angular应用不能没有它。

在这一章，我们将会学习什么是DI，为什么需要它，以及如何使用它。

### 为什么要DI
让我们用以下代码开始。

```typescript
class Engine {}
class Tires {}
class Car {
  private engine: Engine;
  private tires: Tires;
  constructor() {
    this.engine = new Engine();
    this.tires = new Tires();
  }
  // Method using the engine and tires
  drive() {}
}
```

我们的`Car`在它的构造方法里创建所有它需要的东西。这样会有什么问题呢？

问题在于`Car`这个类很脆弱，不灵活，以及难以测试。

`Car`需要引擎（Engine）和轮胎（Tires）。但`Car`的构造方法里直接通过"new"操作符来创建这两个特定类的对象。

如果`Engine`变化了并且构造它需要一个参数，怎么办？此时`Car`就被破坏了，不能被构造出来，除非我们改变这行代码`this.engine = new Engine(theNewParameter)`。在我们刚开始编写`Car`的时候我们并没有考虑过`Engine`的构造参数，事实上我们也并不需要关心。但现在我们被迫要知道，因为一旦`Engine`变化了，`Car`也必须跟着改变。所以说这样的`Car`是很脆弱的。

如果我们想要给`Car`更换一个不同品牌的轮胎，怎么办？这回更糟糕了，`Car`已经固定使用了某种品牌的轮胎（在`Car`的构造方法里直接创建了某种品牌的轮胎）。所以说这样的`Car`是不灵活的。

现在每辆新车都有它自己专用的引擎，引擎不能共享给其他车。你可能觉得这也不是个问题，我们想像一下另外一些应该被共享的东西，例如连接到汽车生产商服务中心的车载无线。我们的`Car`缺乏灵活性去共享那些已经提供给之前的消费者的服务。（想像一下每增加一个消费者，我们的`Car`要为他创建一个专用的服务，成本多高）

当我们要给`Car`测试的时候，我们受限于它的各种隐藏的依赖。想像一下，我们真的要在测试环境去创建一个新的`Engine`？那么`Engine`依赖的东西呢？依赖的依赖呢？另外，一个新的`Engine`实例是否需要一个异步请求去服务器？这种代码难以测试。

**如果车在胎压低时应该发出警报我们该怎样处理？在代码测试的时候，如果不能随意更换轮胎的话，当低压警报响起，我们又怎么断言这个警报是由轮胎引起的呢？** *（此处按自己的理解来翻译了，理解不了原意，原文：What if our `Car` should flash a warning signal when tire pressure is low. How do we confirm that if actually does flash a warning if we can't swap in low-pressure tires during the test?）*

我们没法控制这车的依赖部件。当我们没法控制一个类的依赖，这个类就变得难以测试。

怎么做才能令`Car`更加健壮，更加灵活，更容易测试？

这很容易，我们将`Car`的构造方法改成这样子：

```typescript
constructor(engine: Engine, tires: Tires) {
  this.engine = engine;
  this.tires = tires;
}
```

看到没有，我们将本来在构造方法内部的依赖移到了构造方法的参数上，`Car`这个类不再自己创建引擎和轮胎，只是使用它们。

现在我们创建一个车的实例，并在构造方法传入引擎和轮胎。

```typescript
var car = new Car(new Engine(), new Tires());
```

是不是碉堡了？引擎和轮胎的依赖已经从`Car`这个类本身解耦出来。我们可以传入任何类型的引擎和轮胎，只要它们符合通用的引擎和轮胎的API。

此时如果有人扩展了`Engine`这个类，已经不关`Car`的事了。

> 此时`Car`的消费者的问题来了，他必须更新`Car`的创建代码：
> 
> ```typescript
> var car = new Car(new Engine(theNewParameter), new Tires());
> ```
> 
> 这里的关键点在于：`Car`本身不需要改变。至于消费者的问题，后面我们就会处理，很快就皆大欢喜了。

`Car`变得容易测试了，因为我们完全可以控制它的依赖。我们可以给构造方法传入我们需要的模拟数据去测试：

```typescript
var car = new Car(new MockEngine(), new MockLowPressureTires());
```

**刚才，我们已经掌握了什么是DI。**

DI是一种编程模式，可以令一个类从外部接收它依赖的东西，而非自己创建。

碉堡了！不过，那些可怜的消费者怎么办？任何一个需要`Car`的人必须要手工创建这三样东西：`Car`、`Engine`和`Tires`。这些依赖创建的问题被转移到了消费者身上，我们需要一个东西，它可以帮我们组装这些部件。

我们可以编写一个巨大的类去做这种事情：

```typescript
class SuperFactory {
  createEngine = () => new Engine();
  createTires =  () => new Tires();
  createCar = () => new Car(this.createEngine(), this.createTires());
}
```

你可能觉得这个类一点也不巨大，因为只有三个工厂方法。但是随着应用变得复杂，维护它非常麻烦，这个`SuperFactory`将会变成一个由好多相互依赖的工厂方法组成的巨大蜘蛛网！

如果我们可以简单地列出那些需要创建的东西，而不需要定义谁依赖了什么，这样是否更好？

这时DI框架就跳出来了。假设这个框架就叫`Injector`，我们用`Injector`来注册一些类，并告诉`Injector`如何创建它们。

当我们需要`Car`的时候，就直接请求`Injector`去获取就行了。

```typescript
function main() {
  var injector = new Injector([Car, Engine, Tires, Logger]);
  var car = injector.get(Car);
  car.drive();
}
```

这样就皆大欢喜了。`Car`完全不需要知道如何创建`Engine`和`Tires`，消费者也不需要知道如何创建`Car`，我们也不会有一个巨大的工厂类去维护这些关系。`Car`和消费者都是简单直接地从`Injector`请求他们需要的东西。

这就是**依赖注入框架（Dependency Injection Framework）**。

现在我们知道什么是DI以及它叼炸天的好处，让我们来看一下Angular是怎么实现DI的。

### Angular的依赖注入

Angular自带了DI魔法（框架）。而且这个框架可以作为一个独立的模块用于其他应用或框架。

听起来爽呆了。那我们在创建Angular组件时，它做了些什么？让我们一步步来看。

我们从一个简单版本的`HeroesComponent`开始（完整的看这里[The Tour of Heroes](https://angular.io/docs/ts/latest/tutorial/)）。

```typescript
import {Component} from 'angular2/angular2';
import {Hero} from './hero';
import {HEROES} from './mock-heroes';
@Component({
  selector: 'my-heroes'
  templateUrl: 'app/heroes.component.html'
})
export class HeroesComponent {
  heroes: Hero[] = HEROES;
}
```

这里给`HeroesComponent`提供了一个模拟的heroes列表，并传入到它的`heroes`属性上，绑定在模板中。非常直白。

现在，那些heroes是一个固定在内存的集合，定义在其他文件里，并在这个`HeroesComponent`组件里引入。这在应用刚开始时工作得很好，但是离我们理想的状态还很远。当我们需要测试这个组件，或者需要从服务器获取heroes，我们需要改变这个组件的实现，并且需要处理其他所有使用到`HEROES`模拟数据的地方。

让我们创建一个服务来封装我们获取Hero的数据。

> 在一个单独的文件创建这个服务，为什么要单独一个文件见[这里](https://angular.io/docs/ts/latest/guide/dependency-injection.html#forward-ref)

```typescript
import {Hero} from './hero';
import {HEROES} from './mock-heroes';
class HeroService {
  heroes: Hero[];
  constructor() {
    this.heroes = HEROES;
  }
  getHeroes() {
    return this.heroes;
  }
}
```

`HeroService`公开了一个getHeroes()的方法，并返回了和之前的模拟数据一样的数据，并且所有的使用者都不需要知道这些数据如何得来。

在Angular2中，一个服务（service）就是一个类，和一般的类没有什么区别，直到我们将它注册到Angular的Injector。

#### 配置Injector

我们不需要自己创建Inejctor，Angular会在启动时帮我们创建一个在应用内部使用的Injector。

```typescript
bootstrap(HeroesComponent);
```

让我们在应用启动时配置Injector，通过在第二个参数里添加一个包含`HeroService`的数组。我们稍后会在这章节的[providers](https://angular.io/docs/ts/latest/guide/dependency-injection.html#providers)里解释这个数组。

```typescript
bootstrap(AppComponent, [HeroService]);
```

搞定。此时在整个应用中，Injector就已经知道`HeroService`并且在我们需要的时候注入。

#### 给HeroesComponent注入服务

`HeroesComponent`应从服务里获得heroes。每次使用依赖注入，组件必须在构造方法里”请求“需要的服务（[像我们之前解释的](https://angular.io/docs/ts/latest/guide/dependency-injection.html#ctor-injection)）。

```typescript
constructor(heroService: HeroService) {
  this.heroes = heroService.getHeroes();
}
```

> 这里并不只是添加了一个参数到构造方法里那么简单。
> 
> 我们用typescript编写应用时，需要用在参数后面用":"指定它的类型（`:HeroService`）。这个类也会用`@Component`修饰符来修饰（可以滚动到前面来确认这个事实）。
> 
> 当TypeScript编译器在编译这个类到JavaScript代码时，见到修饰符便会为这个类添加相应的元数据。这些元数据会带有相关的信息说明`heroService`和`HeroService`类是如何关联起来的。
> 
> 这就是为什么Angular的Injector会知道，在创建一个新的`HeroesComponent`时，要注入一个`HeroService`实例。

#### 用Injector创建`HeroesComponent`

在我们介绍Injector时，我们展示了如何用Injector来创建`Car`。

```typescript
var car = injector.get(Car);
```

在Tour of Heroes的整个代码里，我们找不到一行类似这样的代码：

```typescript
var hc = injector.get(HeroesComponent);
```

虽然我们可以写这样的代码，但并没有必要。当我们渲染一个`HeroesComponent`到模板时……

```html
<my-heroes></my-heroes>
```

……或者在通过[router](https://angular.io/docs/ts/latest/guide/router.html)跳转到一个`HeroesComponent`视图的时候，Angular已经帮我们做了这件事。

#### 单例（Singleton）服务

我们可能想知道当我们向其他组件注入`HeroService`时会发生什么，是否会每次都获取到同样的实例？你猜对了，这些依赖都是单例的。我们会在后面这个章节讨论[分级注入](https://github.com/gf-rd/blog/issues/25)。

#### 测试组件

我们在之前强调过为一个类设计依赖注入会使其容易测试。

任务完成！我们甚至不需要Angular的依赖注入系统去测试`HeroesComponent`，我们就这样简单的用一个模拟的服务创建它即可：

```javascript
it("should have heroes when created", () => {
  let hc = new HeroesComponent(mockService);
  expect(hc.heroes.length).toEqual(mockService.getHeroes().length);
})
```

#### 当服务也依赖服务

`HeroService`例子很简单，它自身没有任何依赖。

如果它需要依赖怎么办？假设它需要通过一个日志服务去上报它的行为，如何做？我们可以用同样的“构造器注入”模式。

以下是重写了构造方法后的`HeroService`，构造方法需要一个`logger`参数。

```typescript
import {Injectable} from 'angular2/angular2';
import {Hero} from './hero';
import {HEROES} from './mock-heroes';
import {Logger} from './logger';
@Injectable()
class HeroService {
  heroes: Hero[];
  constructor(private logger: Logger) {
    this.heroes = HEROES;
  }
  getHeroes() {
    this.logger.log('Getting heroes ...')
    return this.heroes;
  }
}
```

现在构造方法会请求注入器注入一个`Logger`的实例，并保存到私有的`logger`属性上。然后我们在`getHeroes()`方法里调用它，这样当任何人请求heroes的时候我们能记录日志。

**看到了吧！@Injectable()修饰器亮瞎了你的眼。**

> **记住一定要写上()！记住一定要写上()！记住一定要写上()！**重要的事情说三遍。一定要这样调用@Injectable()。新手很容易把这东东忘记，如果真的忘记了，我们的应用会发生很奇特的错误。

我们之前都没见到@Injectable()。事实上我们也可以用来修饰`HeroService`，但我们没有使用因为那时并不需要它。

现在我们需要它了……因为我们的service需要注入一个依赖。我们需要它是因为Angular需要构造方法的元数据以用来注入`Logger`。像我们[之前提到](https://angular.io/docs/ts/latest/guide/dependency-injection.html#di-metadata)的一样，TypeScript只会给带有修饰器的类生成元数据。

那么`HeroesComponent`也要注入依赖，为啥不需要@Injectable()修饰器？如果你要的话也可以添加。`HeroesComponent`不需要@Injectable()是因为它已经被@Component修饰了。TypeScript会给任何一个带有修饰器的类生成元数据，然而任何一个修饰器都可以达到这一目的。

### Injector Providers

还记得我们在应用启动时添加了一个包含`HeroService`的数组吧？

```typescript
bootstrap(AppComponent, [HeroService]);
```

这个数组事实上是一个**providers**的列表。

"Providers"会帮我们创建那些从injector注入的实例。有多种可以“提供”一个看起来一样以及具有与`HeroService`相同行为的对象的方式。一个类是个天然的provider——因为它必须被创建（创建了实例才能使用实例方法），但这不是唯一的生成可注入对象的方式。我们可以显式地返回一个对象给injector，我们可以给它提供一个工厂方法去调用。所有这些方法在正常的情况下都是个不错的选择。

重要的是，当有人需要`HeroService`的时候，injector需要知道如何去做。

#### Provider类

当我们写……

```typescript
[HeroService];
```

……我们用了一种简写的表达式去注册到Provider。Angular会展开这个简写，变成一个调用Angular `provider`方法的表达式。

```typescript
[provide(HeroService, {useClass:HeroService})];
```

然后`provider`方法会依次地创建一个新的Angular [Provider类](https://angular.io/docs/ts/latest/api/core/Provider-class.html)的实例：

```typescript
[new Provider(HeroService, {useClass:HeroService})]
```

这个provider的实例会关联到一个包含了可以创建`HeroService`的代码的标识符（token）。

第一个参数就是起到这个[标识符](https://angular.io/docs/ts/latest/guide/dependency-injection.html#token)的作用：定位到这个依赖的值并注册到provider。

第二个参数是一个定义为provider的对象，我们可以称为可以创建依赖值的“配方”。有多种方式可以创建依赖的值……并且也有多种方式去写一个配方。

*译者注：我们可以理解为，第一个参数只是一个表示`HeroService`的标识符（token），通过使用这个标识符，我们可以注入`HeroService`的实例；而第二个参数就是`HeroService`实例的来源，可以有多种定义。*

#### 另一个Class Providers

有时我们会请求一个不同的类去提供类似的服务。

我们经常在测试一个组件的时候使用到创建可替代的Class Provider去提供类似服务这种方法。在这个例子里，我们会告诉injector，当有人需要`HeroService`时，返回一个`MockHeroService`。

```javascript
beforeEachProviders(() => [
  provide(HeroService, {useClass: MockHeroService});
]);
```

#### Value Providers

有时候，提供一个已经创建好的对象，比请求injector创建一个新的实例更容易。

在测试的时候我们经常这样做。我们可能会写以下的测试代码，以验证当`HeroService`返回一个空的hero列表时，`HeroComponent`会怎么执行。

```javascript
beforeEachProviders(() => {
  let emptyHeroService = { getHeroes: () => [] };
  return [ provide(HeroService, {useValue: emptyHeroService}) ];
});
```

注意这里我们用`useValue`而不是`useClass`去定义“配方”。

#### Factory Providers

有时候，最佳的选择不是class也不是value。

假设我们的HeroService有一个酷毙了的新功能，但只提供给某些特定的用户。HeroService不应知道用户，并且我们也不知道当前用户是否特定用户——直到应用运行的时候。我们决定扩展`HeroService`的构造方法，接受一个`useCoolFeature`的标志去控制新功能的开关。我们改写如下：

```typescript
@Injectable()
class HeroService {
  heroes: Hero[];
  constructor(private logger: Logger, private useCoolFeature: boolean) {
    this.heroes = HEROES;
  }
  getHeroes() {
    let msg = this.useCoolFeature ? 'the cool new way' : 'the old way';
    this.logger.log('Getting heroes ...' + msg)
    return this.heroes;
  }
}
```

这个新功能的标志纯粹是个布尔值，我们可以注入这个值，但为了这个值去写一个新的类显然很蠢。

我们用一个工厂方法去替换`HeroService`的provider，以便为当前用户创建一个正确配置的`HeroService`。

```typescript
let heroServiceFactory = (logger: Logger, userService: UserService) => {
  return new HeroService(logger, userService.user.isSpecial);
}
```

> 这个工厂接受两个参数：logger服务和user服务。logger服务像之前那样，我们直接传入；我们知道如果userService.user.isSpecial的值为true，我们能用到新的功能，但我们要直到运行时才真正知道谁能用到。

依赖注入无处不在，此处的工厂方法依赖两个注入的服务：`Logger`和`UserService`。我们这样声明provider的对象定义：

```typescript
let heroServiceDefinition = {
   useFactory: heroServiceFactory,
   deps: [Logger, UserService]
};
```

> `useFactory`属性会告诉Angular，这个provider是个工厂方法，并且这个工厂方法的实现是`heroServiceFactory`。
> 
> `deps`属性则是一个provider标识符（token）数组。`Logger`和`UserService`类则分别标识了它们对应的provider类。

最后，我们创建一个provider（下面的heroServiceProvider），并修改启动方法，包含在这个provider上注册的provider们（即Logger和UserService）。

```typescript
let heroServiceProvider = provide(HeroService, heroServiceDefinition);
bootstrap(AppComponent, [heroServiceProvider, Logger, UserService]);
```

#### 字符串标识符

有时候我们会用对象依赖而不用类依赖。

应用程序经常会定义配置对象，记录了各种配置值，比如应用的标题，或者一个web api端的地址。这些配置对象一般都不是某个类的实例，它们纯粹是个普通的对象……例如这个：

```typescript
let config = {
  apiEndpoint: 'api.heroes.com',
  title: 'The Hero Employment Agency'
};
```

我们希望将这个`config`对象也可以被注入。我们知道可以用"Value Provider"去注册一个对象，但这种情况下，我们用什么做标识符？

直到现在，不管我们是用class、value还是factory来写provider，我们一直用class来充当标识符的角色（上面例子中一直用的`HeroService`）。而这回我们并没有一个类来作为标识符，没有一个叫`Config`的类。

幸运的是，标识符可以是一个字符串，一个类，或者一个[OpaqueToken](https://angular.io/docs/ts/latest/api/core/OpaqueToken-class.html)对象。在Angular内部，`Provider`会将作为标识符参数的字符串、类都转换成为`OpaqueToken`；injector会用这个token来定位依赖的值或providers。

以下我们就居于字符串来将我们的配置对象注册为标识符！

```typescript
bootstrap(AppComponent, [
  // 其他 providers //
  provide('App.config', {useValue:config})
]);
```

让我们将刚掌握的字符串标识符应用于`HeroesComponent`，修改其构造方法以显示配置的title。现在我们的构造方法变成：

```typescript
constructor(heroService: HeroService)
```

我们可能天真地认为可以这样添加`config`依赖：

```typescript
// FAIL!
constructor(heroService: HeroService, config: config)
```

然而这并不起作用，并没有一个叫`config`的类型，并且我们没有用任何名称注册了`config`对象。我们需要借助Angular的另一个修饰器@Inject。

```typescript
import {Inject} from 'angular2/angular2'
constructor(heroService: HeroService, @Inject('app.config') config)
```

### 下一步

在这一章，我们已经学习了Angular的依赖注入的基本概念。

Angular的DI的能力远不只我们描述的那种，我们可以学习更多高级的功能，可以在[分级注入](https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html)章节看看它的嵌套injector。

### 附录：为什么我们推荐一个文件一个类

开发者更希望一个文件写一个类，一个文件里写多个类会令人迷惑，最好避免这样做。如果我们在单独的文件定义每个类，那就没有下文的担忧了。所以请忽略下文继续阅读！

如果我们忽略这个建议，然后无论如何都要在`HeroesComponent`这个文件里添加`HeroService`这个类，**那么请在最后定义`HeroesComponent`！**如果我们在服务之前定义这个类，将会得到运行时的空引用错误（runtime null reference error）。

为了明白这是为什么，复制以下错误的、极其简单的示例代码到[TypeScript playground](http://www.typescriptlang.org/Playground)去试一下就知道了。

```typescript
class HeroesComponent {
  static $providers=[HeroService]
}
class HeroService { }
alert(HeroesComponent.$providers)
```

> `HeroService`错误地在`HeroesComponent`之后才定义。
> 
> 静态属性`$providers`代表了TypeScript编译器向组件类注入的与`HeroService`相关的元数据。
> 
> `alert`调用则模拟了在运行时DI会尝试创建一个`HeroesComponent`的操作。

点击Run运行这段代码。alert弹出来了但什么也没显示，这相当于在运行时抛出了空引用错误。

当我们看到转换成JavaScript后的代码就明白了：

```javascript
var HeroesComponent = (function () {
    function HeroesComponent() {
    }
    HeroesComponent.$providers = [HeroService];
    return HeroesComponent;
})();
var HeroService = (function () {
    function HeroService() {
    }
    return HeroService;
})();
alert(HeroesComponent.$providers);
```

注意，TypeScript编译器会将类转换成函数表达式，并赋值给变量。当`$providers`数组赋值的时候，获得的`HeroService`的值还是undefined。当`HeroService`真正赋值的时候已经太迟了。

调整一个这两个类的定义顺序，使得`HeroService`出现在`HeroesComponent`需要它之前。再运行一次，这回alert能正确地显示`HeroService`的函数定义。

如果我们仍然坚持将`HeroService`定义在同一个文件并且坚持要先定义组件，Angular也提供了一个方法使得它能正常工作（汗。。。）。`forwardRef()`方法就是干这事的，它让我们可以在定义一个类之前引用它。要了解更多相关问题和`forwardRef()`方法请戳[这个文章](http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html)。

>### 下一章
> [7. 模板语法](https://github.com/gf-rd/blog/issues/18)

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
