### ISSUE TITLE
【Angular2开发指南】10.生命周期钩子

### ISSUE THREAD

**Issue by zhenyong** [gf-rd/blog#13]
组件的生命周期
===

在 Angular 的管理下，每个组件都有自己的一套生命周期，表现在：创建、渲染组件以及嵌套组件；绑定的数据改变时检测组件；对应 dom 节点移除前销毁组件。

Angular 提供了 **钩子方法**，允许我们在组件的生命周期各阶段作出响应

本章会通过示例讲解钩子方法的用途。

[运行示例](https://angular.io/resources/live-examples/lifecycle-hooks/ts/plnkr.html)

## 生命周期钩子

指令或组件实例都有一套生命周期，表现在 Angular 对它们的创建、更新和销毁。

开发者可以实现一个或者多个 “生命周期钩子（接口）” ，从而在生命周期的各阶段作出适当的处理。这些钩子接口包含在 `angular2/core` 中。

以下是所有的生命周期钩子接口：

- `OnInit`
- `OnDestroy`
- `DoCheck`
- `OnChanges`
- `AfterContentInit`
- `AfterContentChecked`
- `AfterViewInit`
- `AfterViewChecked`

现有的指令和组件只用到部分接口，而且某些接口只对组件有效。

每个接口包含一个钩子方法，其名称为接口名称加上前缀 `ng`。例如 `OnInit` 接口就有 `ngOnInit` 钩子方法。

Angular 会依序调用下列钩子方法：

- ngOnChanges - 当输入/输出绑定的值改变时调用
- ngOnInit - 在第一次 ngOnChanges 后调用
- ngDoCheck - 自定义的方法，检测和处理值的改变
- ngAfterContentInit - 在组件内容初始化之后调用
- ngAfterContentChecked - 组件每次检查内容时调用
- ngAfterViewInit - 组件相应的视图初始化之后调用
- ngAfterViewChecked - 组件每次检查视图时调用
- ngOnDestroy - 指令销毁前调用。

[运行示例](https://angular.io/resources/live-examples/lifecycle-hooks/ts/plnkr.html) ，演示如何使用这些接口

## Peek-a-boo (示例中的组件)

PeekABooComponent 组件演示了几乎所有钩子方法。

> 就剩 DoCheck 接口没用上，如果我们的组件使用了 ngDoCheck 方法来替换 Angular 默认的 “检测处理改变”，那么就不应该用 ngOnChanges 方法了。也就是说，ngOnChanges 和 ngDoCheck 只能用一个。

>自定义“检测改变” 和 ngDoCheck 的相关文档还在完善中。

Peek-a-boo 只是一个例子，实际上我们很少会去实现所有的钩子接口。

我们以后会更新本章的内容，尽可能的讲解 Peek-a-boo 和其他关于生命周期钩子的案例，在这之前，您自个好好看 [示例](http://plnkr.co/edit/?p=preview) 享受学习吧。

## 一定要实现接口吗?

如果你不实现接口而直接用对应的钩子方法是不会报错的，不过，我们还是建议你写上实现接口的代码，这样可以利用 TypeScript 的强类型检测和某些编辑器的特性。

事实上，在 TypeScript 转化为 Javascript 之后，你是看不到`implements OnInit` 这些代码的，而且在运行的时候 Angular 也执行不到这些代码。也就是说，把这些代码放到不支持接口的语言（例如纯 Javascript）里跑是没意义的。

所幸，接口不是必须的，我们无须添加接口实现来使用生命周期钩子方法。

Angular 不会用接口那一套概念，而是检查指令和组件类，然后调用定义好的钩子方法，例如 `ngOnInit()`。

>### 下一章
> [11. 属性指令](https://github.com/gf-rd/blog/issues/22)

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
