### ISSUE TITLE
【Angular2开发指南】8. 管道

### ISSUE THREAD

**Issue by JTangming** [gf-rd/blog#16]
`管道`（pipes）是用来转换、显示模板内的值。

任何应用都开始于这样一个简单的任务：获取数据，转换然后展示给用户。

获取数据可能像创建一个局部变量一样简单，但也有可能复杂如WebSocket的数据流一样。

一旦获取到数据，我们直接将它们最原始的数据转换成字符串后展示到屏幕上，这不是一个很好的用户体验，几乎所有的用户都喜欢简单的生日数据(April 15，1988)而不是最原始的字符串格式 (Fri Apr 15 1988 00:00:00 GMT-0700 (Pacific Daylight Time)).

显然一些值经过一定的推敲，在一个应用或者其它应用中，我们发现我们更希望复用许多相同的转换，我们几乎认为它们如同样式一样，实际上，我们更倾向于像用样式一样来应用到我们的html模板中。

欢迎，Angular pipes，可以在我们的html中声明一种简单的数据转换格式。

[线上例子]
(http://plnkr.co/edit/?p=preview)

### 管道 (pipes)的使用

管道是将拿到的数据转换成我们想要的输出格式，下面我们将演示一个组件，把属性`生日日期`转换成一个友好的日期：

app/hero-birthday1.component.ts
```javascript
import {Component} from 'angular2/core'
@Component({
selector: 'hero-birthday',
    template: `<p>The hero's birthday is {{ birthday | date }}</p>`
})
export class HeroBirthday {
    birthday = new Date(1988,3,15); // April 15, 1988
}
```
组件的模板是这样的
```
<p>The hero's birthday is {{ birthday | date }}</p>
```
在内嵌的表达式中，我们输出生日组件的值是通过[pipe操作符](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#pipe)(|)右边的[Date pipe](https://angular.io/docs/ts/latest/api/common/DatePipe-class.html)方法来实现的，所有的管道都是这样的机制。

### 管道(pipes)内置的方法

Angular有一套常用的<a name="somesth">管道</a>，如DatePipe, UpperCasePipe, LowerCasePipe, CurrencyPipe和PercentPipe. 在任何模板中都可以便捷使用。

### 定义管道(pipes)参数

管道可以有一定数量的可选参数来调整其输出。

我们给管道添加参数是通过在管道名后面的冒号（:）来添加参数值，如（, currency:'EUR'），如果我们的管道接受多个参数的话，我们将用冒号来区分开。

我们将修改我们的生日模板来给出一个格式化的参数，格式化后主人公的April 15th生日将会显示成04/15/88.
```
<p>The hero's birthday is {{ birthday | date:"MM/dd/yy" }} </p>
```
参数的值可以是任意合法的模板表达式，如字符串或者属性组件等，也就是说，我们可以控制我们的格式通过绑定来控制生日的值。

我们再写一个组件来绑定管道的格式化参数到这个组件的参数上，下面是这个组件的模板。
app/hero-birthday2.component.ts (template)
```
template: `
     <p>The hero's birthday is {{ birthday | date:format }}</p> 
     <button (click)="toggleFormat()">Toggle Format</button>
 `
```
我们在模板上再添加一个按钮，通过绑定click事件到组件的toggleFormat方法上，这个方法是在一个短的表单和一个长的表单间来切换该组件的format属性。
app/hero-birthday2.component.ts (class)
```javascript
export class HeroBirthday {
    birthday = new Date(1988,3,15); // April 15, 1988
    toggle = true; // start with true == shortDate
    get format() { 
        return this.toggle ? 'shortDate' : 'fullDate'
    }
    toggleFormat() { this.toggle = !this.toggle; }
}
```
当我们点击这个按钮，将会在"04/15/1988"、 "Friday, April 15, 1988"间来回显示。

![](https://raw.githubusercontent.com/JTangming/tm/master/images/date-format-toggle-anim.gif)

想要了解更多DatePipes，请参考[API Docs]
(https://angular.io/docs/ts/latest/api/core/DatePipe-class.html).

### 链式管道

我们可以链式的书写管道到一个实用的组合体上，下面的例子，我们将birthday链到DatePipe和UpperCasePipe上以便我们将生日日期显示为大写，下面的日期将会是APR 15, 1988
```
<p> The chained hero's birthday is {{ birthday | date | uppercase}} </p>
```
如果我们通过参数来过滤，那么我们可以通过括号来控制编译的顺序，下面的例子将显示FRIDAY, APRIL 15, 1988
```
<p> The chained hero's birthday is {{ birthday | date:'fullDate' | uppercase}} </p>
```
通过括号来区分优先级或者让表达式更新清楚
```
<p> The chained hero's birthday is {{ ( birthday | date:'fullDate' ) | uppercase}} </p>
```

### 自定义管道(pipes)

我们可以自定义管道。
下面自定义一个名为ExponentialStrengthPipe的pipe。
app/exponential-strength.pipe.ts
```javascript
import {Pipe} from 'angular2/core';
/*
* Raise the value exponentially
* Takes an exponent argument that defaults to 1.
* Usage:
* value | exponentialStrength:exponent
* Example:
* {{ 2 | exponentialStrength:10}}
* formats to: 1024
*/
@Pipe({name: 'exponentialStrength'})
export class ExponentialStrengthPipe {
transform(value:number, args:string[]) : any {
 return Math.pow(value, parseInt(args[0] || '1', 10));
 }
}
```
这个管道例子有几个关键的点：
- 管道是一个带有管道元数据的类；
- 这个类实现一个转换方法，通过一个输入值和一个可选的数组字符参数，最终返回转换后的值；
- 数组参数中的某一项将每一个参数传递给管道；
- 我们通知Angular这是一个引入过Angular核心库的@Pipe服务；
- 这个@Pipe服务带有一个参数，该参数它的值是一个管道名，我们将使用在一个模板表达式中，它可以是一个合法的Javascript定义，我们的管道名是exponenentialStrength。

那么我们现在需要一个组件来论证我们的pipe
app/power-booster.component.ts
```javascript
import {Component} from 'angular2/core';
import {ExponentialStrengthPipe} from './exponential-strength.pipe';
@Component({
    selector: 'power-booster',
    template: `
        <h2>Power Booster</h2>
        <p>
            Super power boost: {{2 | exponentialStrength: 10}}
        </p>
     `,
    pipes: [ExponentialStrengthPipe]
})
export class PowerBooster { }
```
![](https://raw.githubusercontent.com/JTangming/tm/master/images/power-booster.png)
有两点注解：
1、我们使用自定义的管道和内置的管道是一样的;
2、我们必须在一个带有管道数组的组件中列出我们的管道.

`记住这些管道数组`
如果我们忽视去列出我们的自定义管道的话，Angular将会报错。我们不需要在先前的例子中列出DatePipe是因为所有Angular内置的管道是预先注册过的，自定义的管道必须手动注册。

如果我们想试试[线上的例子](http://plnkr.co/edit/?p=preview)，我们可以通过改变模板中的值和可选的指数来观测它的行为改变

### Power Boost Calculator (extra-credit)

更新模板来测试我们的自定义pipe没有多大的乐趣，我们可以升级这个例子为一个"Power Boost Calculator" ，它将我们的pipe和双向数据绑定结合到ngModel。
/app/power-boost-calculator.component.ts
```javascript
import {Component} from 'angular2/core';
import {ExponentialStrengthPipe} from './exponential-strength.pipe';
@Component({
    selector: 'power-boost-calculator',
    template: `
        <h2>Power Boost Calculator</h2>
        <div>Normal power: <input [(ngModel)]="power"></div>
        <div>Boost factor: <input [(ngModel)]="factor"></div>
       <p>
             Super Hero Power: {{power | exponentialStrength: factor}}
       </p>
    `,
     pipes: [ExponentialStrengthPipe]
})
export class PowerBoostCalculator {
    power = 5;
    factor = 1;
}
````
![](https://raw.githubusercontent.com/JTangming/tm/master/images/power-boost-calculator-anim.gif)

### 管道状态

管道有两种状态，无状态的和有状态的。

无状态的管道是一个纯粹的函数，流入的数据将不会记录任何东西，或者不会导致任何的副作用。

大多数的管道是无状态的，我们第一个例子的Datapipe就是一个无状态的管道，所以这是我们自定义的ExponentialStrengthPipe。

有状态的管道在概念上类似于面向对象编程类，它们可以管理数据的变换，管道创建一个HTTP请求，存储它的返回和显示结果，是一个有状态的管道。检索或请求数据的管道应该要谨慎使用，因为使用网络数据往往会引入错误的条件，在javascript中处理更优于在模板中处理。我们可以为了特定的后端和基本的异常捕获而创建自定义的管道来减轻任何风险。

### 有状态异步管道

Angular异步的管道是一个有状态的管道标志性例子，异步的管道能收到一个Promise对象或者监测输入和自动订阅输入，最终返回一个可触发的值。

它的有状态性是因为管道维护一个输入的订阅并且它的返回值也依赖于这个订阅器。

下面的例子，我们将用异步的pipe绑定一个简单的promise给一个view。
app/hero-async-message.component.ts
```javascript
import {Component} from 'angular2/core';
// Initial view: "Message: "
// After 500ms: Message: You are my Hero!"
@Component({
    selector: 'hero-message',
    template: 'Message: {{delayedMessage | async}}',
})
export class HeroAsyncMessageComponent {
    delayedMessage:Promise<string> = new Promise((resolve, reject) => {
        setTimeout(() => resolve('You are my Hero!'), 500);
    });
}
```
异步的管道保存样板在这份组件代码中。组件不需要订阅异步数据源，它不会为了绑定而提取完成的数据和暴露他们。（在像事件触发器监测数据源的情形下）当这个组件销毁的时候也不需要去退订绑定的事件（潜在的内存泄露）。

### 实现一个有状态的管道

默认情况下管道是无状态的，我们必须声明一个有状态的管道，即通过设定特定的参数@Pipe为false，这个设置将告诉Angular改变监测系统去检查每一次循环管道的输出，不论结果是否有改变。

这里我们将装饰一个新的有状态的FetchJsonPipe，将发起一个HTTP请求来获取返回结果和显示服务器返回的这些数据：
app/fetch-json.pipe.ts (metadata)
```javascript
@Pipe({
    name: 'fetch',
    pure: false
})
```
接下来我们将完成这个管道，它在终端输入一个url来返回一个JSON文件，这个管道将发起一个一次性的异步请求到服务端并且最终收到一个JSON的返回。
app/fetch-json.pipe.ts
```javascript
import {Pipe} from 'angular2/core';
@Pipe({
    name: 'fetch',
    pure: false
})
export class FetchJsonPipe {
    private fetchedValue:any;
    private fetchPromise:Promise<any>;
    transform(value:string, args:string[]):any {
    if (!this.fetchPromise) {
         this.fetchPromise = window.fetch(value)
        .then((result:any) => result.json())
        .then((json:any) => this.fetchedValue = json);
    }
    return this.fetchedValue;
 }
}
```
接下来我们将在一个定义了两个绑定的模板的测试组件中演示这个管道。
app/hero-list.component.ts (template)
```
template: `
<h4>Heroes from JSON File</h4>
<div *ngFor="#hero of ('heroes.json' | fetch) ">
{{hero.name}}
</div>
<p>Heroes as JSON:
{{'heroes.json' | fetch | json}}
</p>
`,
```
渲染结果如下：

![](https://raw.githubusercontent.com/JTangming/tm/master/images/hero-list.png)

第一个绑定是直接在最前面的，另一个ngFor重复的显示从JSON文件源获取到的英雄的名字，通过自定义的获取管道，我们定义这个文件名为"heroes.json"。

### JsonPipe

第二个绑定使用了更多的管道链，将JSON格式传入到内置的JsonPipe，我们获取到了相同的结果和展示了规则的英雄数据。

`用JSON PIPE来DEBUGGING`
JsonPipe是一个简单的方法来诊断一个神秘失败数据绑定

这是完整的组件实现:
app/hero-list.component.ts
```javascript
import {Component} from 'angular2/core';
import {FetchJsonPipe} from './fetch-json.pipe';
@Component({
    selector: 'hero-list',
    template: `
          <h4>Heroes from JSON File</h4>
          <div *ngFor="#hero of ('heroes.json' | fetch) ">
              {{hero.name}}
          </div>
          <p>Heroes as JSON:
               {{'heroes.json' | fetch | json}}
          </p>
    `,
    pipes: [FetchJsonPipe]
})
export class HeroListComponent {
     /* I've got nothing to do ;-) */
}
``` 

管道是一种伟大的方式来封装和共享相同的展示数据，我们使用它们就像是样式一样，把他们引入到我们的模板表达式中来丰富我们的展示和在模板中的实用性。

>### 下一章
> [9、路由 & 导航](https://github.com/gf-rd/blog/issues/28)

**Comment by JTangming** [comment]
review修复 : 
 - 语句语病等的修改；
 - 加上代码运行结果图片；
 - 排版格式修改

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
