### ISSUE TITLE
【Angular2开发指南】1. Angular 备忘小抄

### ISSUE THREAD

**Issue by gaohailang** [gf-rd/blog#17]
> 注意：在本份文档中，先有代码的示例，然后才是代码的说明和解释。请阅读中留意~

## 启动
`import {bootstrap} from 'angular2/angular2';`

```js
bootstrap​(MyAppComponent, [MyService, provide(...)]);
```
启动以MyAppComponent为根组件的应用程序，同时配置依赖注入提供者 

## 模板语法

```js
<input [value]="firstName">
```
绑定firstName表达式的结果到特性 value上

```js
<div [attr.role]="myAriaRole">
```
绑定myAriaRole表达式的结果到属性 value上

```js
<div [class.extra-sparkle]="isDelightful">
```
绑定表达式 isDelightful 的布尔值结果到元素的css类 extra-sparkle 的存在与否上

```js
<div [style.width.px]="mySize">
```
绑定表达式mySize的结果到样式特性width上 。单位是可选的

```js
<button (click)="readRainbow($event)">
```
当click事件在按钮元素（或其子元素）上被触发时，调用 readRainBow 方法，传入 event事件对象

```js
<div title="Hello {{ponyName}}">
```
绑定特性的值到内插字符串中，如"Hello Seabisuit"。等价于`<div [title]="'Hello' + ponyName">`

```js
<p>Hello {{ponyName}}</p>
```
绑定内插字符串的值到文本内容中，如 "Hello Seabiscuit"

```js
<my-cmp [(title)]="name">
```
设置双向数据绑定

```js
<video #movieplayer ...>
  <button (click)="movieplayer.play()">
</video>
```
在当前的模板中，创建一个局部变量 moiveplayer 在video元素实例中的数据绑定和事件绑定表达式时提供访问

```js
<p *myUnless="myExpression">...</p>
```
`*`符号意味着当前元素是被转变成内嵌模板，等价于`<template [myUnless]="myExpression"><p>...</p></template>`

```js
<p>Card No.: {{cardNumber | myCreditCardNumberFormatter}}</p>
```
通过叫 creditCardNumberFormatter 管道，转变表达式 cardNumber 的当前值

```js
<p>Employer: {{employer?.companyName}}</p>
```
？操作符意味着 employer 字段是可选的如果当它是未定义时。剩余的表达式被忽略

## 内置指令
`import {NgIf, ...} from 'angular2/common';`

```js
<section *ngIf="showSection">
```
根据showSection表达式的值，移除或者重新创建该部分的DOM树

```js
<li *ngFor="#item of list">
```
通过ngFor指令来为列表中的每一个元素创建实例化一个view，把li元素和它的内容变成模板

```js
<div [ngSwitch]="conditionExpression">
  <template [ngSwitchWhen]="case1Exp">...</template>
  <template ngSwitchWhen="case2LiteralString">...</template>
  <template ngSwitchDefault>...</template>
</div>
```
根据当前条件表达式的值，通过选择其中内嵌模板，动态替换该div的内容

```js
<div [ngClass]="{active: isActive, disabled: isDisabled}">
```
把元素上的css类添加与否和关联映射值的真假上。右侧的表达式应该类似{class-name: true/false}的映射map

## 表单
`import {FORM_DIRECTIVES} from 'angular2/common';`

```js
<input [(ngModel)]="userName">
```
提供双向数据绑定，解析和验证表单项的数据

## 类装饰器
`import {Directive, ...} from 'angular2/core';`

```js
@Component({...})
class MyComponent() {}
```
装饰一个是组件并且提供组件的元数据信息的类

```js
@Pipe({...})
class MyPipe() {}
```
装饰一个是管道并且提供管道的元数据信息的类

```js
@Injectable()
class MyService() {}
```
装饰一个有在构造函数中指名依赖，同时在当注入器创建该类实例时会被注入的类

## 指令配置
`@Directive({ property1: value1, ... })`

```js
selector: '.cool-button:not(a)'
```
申明一个用于在模板中标识指令的CSS选择器。支持的选择器包括： `element`, `[attribute]`, `.class` 和 `:not()`;

```js
providers: [MyService, provide(...)]
```
为该指令和它的子指令所需的依赖注入提供器数组

## 组件配置
`@Component extends @Directive, so the @Directive`
配置同样也适用于组件

```js
viewProviders: [MyService, provide(...)]
```
该组件视图中所需的依赖注入提供者数组

```js
template: 'Hello {{name}}'
templateUrl: 'my-component.html'
```
组件视图中的内联模板/外部模板URL

```js
styles: ['.primary {color: red}']
styleUrls: ['my-component.css']
```
给组件视图提供样式的 内联CSS样式/外部样式表URLs 列表

```js
directives: [MyDirective, MyComponent]
```
组件模板中使用的指令列表

```js
pipes: [MyPipe, OtherPipe]
```
组件模板中使用的管道列表

## 指令和组件的改变检查和生命周期钩子

```js
constructor(myService: MyService, ...) { ... }
```
在任何生命周期钩子前，类的构建函数被调用。通过这个来注入依赖，同事避免不要多太多工作在这

```js
ngOnChanges(changeRecord) { ... }
```
输入属性改变后和在处理它的内容或子视图前，该hook被调用

```js
ngOnInit() { ... }
```
在构造函数后被调用，来初始化输入属性，同时第一次调用 ngOnChanges

```js
ngDoCheck() { ... }
```
当组件或指令的输入属性被检查后，该hook总被调用。通过实时特殊的检查，来用它扩展改变探测。

```js
ngAfterContentInit() { ... }
```
在组件或指令的内容被初始化后该hook被调用

```js
ngAfterContentChecked() { ... }
```
当组件或指令的内容被检查后该hook被调用

```js
ngAfterViewInit() { ... }
```
当组件的视图被初始化后，同时在ngAfterContentInit被调用后。只适用于组件。

```js
ngAfterViewChecked() { ... }
```
当组件的内容被检查后该hook被调用

```js
ngOnDestroy() { ... }
```
只被调用一次。在实例被消除前。

## 依赖注入
`import {provide} from 'angular2/core';`

```js
provide(MyService, {useClass: MyMockService})
```
设置或覆盖 MySerivce 的提供者为 MyMockService 类

```js
provide(MyService, {useFactory: myFactory})
```
设置或覆盖 MySerivce 的提供者为 MyFactory 工厂方法

```js
provide(MyValue, {useValue: 41})
```
设置或覆盖 MyValue 的提供者为 41

## 路由和导航

```js
@RouteConfig([
  { path: '/:myParam', component: MyComponent, as: 'MyCmp' },
  { path: '/staticPath', component: ..., as: ...},
  { path: '/*wildCardParam', component: ..., as: ...}
])
class MyComponent() {}
```
配置为装饰组件的路由。支持静态，参数和通配符的路由。

```js
<router-outlet></router-outlet>
```
标记的该位置为加载当前路由的组件

```js
<a [routerLink]="[ '/MyCmp', {myParam: 'value' } ]">
```
创建一个链接到基于路由指令包括一个路由名称及可选参数的不同看法。路由名称配置的路由的财产相匹配。添加'/'前缀导航至一个根路线;添加“./”前缀，孩子的路线。

```js
@CanActivate(() => { ... })class MyComponent() {}
```
组件装饰器，定义了由路由先去调用看是否需要激活组件的方法。该方法需要返回一个布尔值或者是promise

```js
routerOnActivate(nextInstruction, prevInstruction) { ... }
```
当导航到组件时，路由来调用组件的 routerOnActivate 方法（如果被定义）

```js
routerCanReuse(nextInstruction, prevInstruction) { ... }
```
路由调用组件的 routerCanReuse 方法（如果被定义）来决定是否复用实例还是要摧毁实例重新创建。该方法需要返回一个布尔值或者是promise

```js
routerOnReuse(nextInstruction, prevInstruction) { ... }
```
路由调用组件的 routerOnReuse 方法（如果被定义）当它需要重用组件实例时

```js
routerCanDeactivate(nextInstruction, prevInstruction) { ... }
```
当浏览新页面，路由调用所以可能别移除的组件的 routerCanDeactivate方法（如果被定义）。只有当所有方法返回true或者是promise被resolved，你页面浏览才会被处理

```js
routerOnDeactivate(nextInstruction, prevInstruction) { ... }	
```
该方法当路由改变同时指令被移除后被调用。可以返回一个promise，从而在promise被resolve前阻止组件被移除

>### 下一章
> [2. 架构综述](https://github.com/gf-rd/blog/issues/23)

**Comment by hstarorg** [comment]
习惯先看说明，再看代码。文章是反着来的...

**Comment by hstarorg** [comment]
本文”指令和组件的改变检查和生命周期钩子“段的最后一句代码展示有误

**Comment by gaohailang** [comment]
@hstarorg 看的很仔细，多谢指正~

- 关于代码示例和解释的前后顺序，我现在在文档前加上了特殊说明，希望提醒下阅读的朋友👬们
- 关于组件和指令的生命周期钩子的destroy的代码示例已经改正。

**Comment by hstarorg** [comment]
@gaohailang 可以考虑下把文字说明和代码交换一下哇。。

**Comment by Yunfei1982** [comment]
后面部分翻译的一塌糊涂，机器翻译的吗？

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
