### ISSUE TITLE
【Angular2开发指南】3.数据显示

### ISSUE THREAD

**Issue by lizhonghui** [gf-rd/blog#19]
在Angular里，我们通过绑定组件属性到HTML模板元素里，使用插值标记或者其他形式的属性绑定来展示数据。

## 显示组件属性
我们在Angular里显示数据通常是通过将HTML模板里的各种控件元素和Angular的组件属性关联绑定。在这个章节里，我们会编写一个关于英雄人物的组件，组件显示出每个英雄的名字，选中一个英雄时会在列表下方展示英雄的详细信息。
最终的UI图会像下面那样

![最终UI图](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/3-final.png)

## 使用插值显示组件属性
显示组件属性的最简单方法是通过插值绑定对应的属性名，使用闭合的双大括号插值我们可以把属性名放置在HTML模板里。
我们一起动手来编写一个小示例。
新建一个项目文件夹`displaying-data`，根据[QuickStart](https://angular.io/docs/ts/latest/quickstart.html)的步骤来操作。
然后打开`app.component.ts`文件，修改模板和组件类代码。修改完后代码类似下面这样

```Javascript
import {Component} from 'angular2/core';
@Component({
  selector: 'my-app',
  template: `
    <h1>{{title}}</h1>
    <h2>My favorite hero is: {{myHero}}</h2>
    `
})
export class AppComponent {
  title = 'Tour of Heroes';
  myHero = 'Windstorm';
}
```

可以看到，我们在之前`QuickStart`空空的组件类里添加了两个属性：`title`和`myHero`。
修改后的模板使用闭合的双大括号插值显示新增的两个组件属性。

```Javascript
template: `
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero}}</h2>
  `
```

>上面的模板是多行文本，包含在反引号（`）里，这是ECMAScript 2015的特性，反引号跟单引号并不是同一个字符，反引号有很多优异的特性，我们正在使用的就是支持多行文本，使我们的HTML代码更具有可读性。

Angular组件会自动给`title`和`myHero`赋值，并把值插入到浏览器里，且当值发生改变时，自动更新显示。

>更确切的说，触发更新显示的时机是在视图上的某些异步事件之后，例如键盘事件，timer事件，或异步XHR返回。在这个示例里并没有包含这些事件，所以示例上的那些属性并不会自己更新，这我们必须先如实说明。

代码里我们并没有显式通过`new`操作去创建一个`AppComponent`的实例，而是Angular自动为我们创建好了，这个过程是怎样的呢？

请看在`@Component`修饰符里的CSS选择器`selector`，该选择器声明了一个叫`my-app`的元素，回想起`QuickStart`里面我们添加了`my-app`元素到`index.html`的body里。

```HTML
<body>
  <my-app>loading...</my-app>
</body>
```

当我们调用bootstrap方法（见`boot.ts`）启动`AppComponent`时，Angular会在`index.html`查找`<my-app>`，找到之后即实例化`AppComponent`，将生成的模板片段插入到`<my-app>`这个元素里。

至此，代码修改完毕，执行npm script里定义的脚本来运行程序，在运行过程中脚本会自动检测更新并实时编译。

```bash
npm start
```

如图，运行之后可以看到标题和英雄的名字。

![标题和英雄](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/3-title-and-hero.png)

让我们回顾一下示例里所选的方案，看是否有其他替代方案。

## 内联模板还是外联模板
模板的声明有两种不同的方案。一种是内联模板，即直接赋值在`@Component`里的`template`属性，如本示例；另一种是外联模板，模板是放置在独立的文件里，通过`@component`里的`templateUrl`属性与组件关联。
本示例中，模板本身很短，使用内联模板可以使代码更简洁。选择哪种方式主要取决于你的代码风格，上下文环境以及代码组织形式。
无论是哪种方式，数据的绑定方式都是一致的。

#构造函数初始化还是变量赋值初始化
使用类的变量赋值初始化组件属性是一种非常简洁紧凑的写法。
有些人喜欢用构造函数初始化组件属性，像下面那样：

```Javascript
export class AppCtorComponent {
  title: string;
  myHero: string;

  constructor() {
    this.title = 'Tour of Heroes';
    this.myHero = 'Windstorm';
  }
}
```

这种方式也可以，选择哪种方式取决于你的代码风格和代码组织形式，本示例采用更加简洁变量赋值方式仅仅是因为代码量更少。

## 使用`NgFor`显示数组
我们想要在示例里显示英雄列表，须在组件里添加英雄列表的模拟数据，放在`myHero`上面，同时以数组的第一个值重新赋值给`myHero`。

```Javascript
export class AppComponent {
  title = 'Tour of Heroes';
  heroes = ['Windstorm', 'Bombasto', 'Magneta', 'Tornado'];
  myHero = this.heroes[0];
}
```

现在我们在模板里加入`NgFor`遍历指令去显示英雄列表里的每一项。

```HTML
  template: `
    <h1>{{title}}</h1>
    <h2>My favorite hero is: {{myHero}}</h2>
    <p>Heroes:</p>
    <ul>
      <li *ngFor="#hero of heroes">
        {{ hero }}
      </li>
    </ul>
  `
```

代码的样子是大家熟悉的HTML无序列表`<ul>`和`<li>`，我们看`<li>`标签。

```HTML
<li *ngFor="#hero of heroes">
  {{ hero }}
</li>
```

我们添加了略神秘的`*ngFor`到`<li>`元素，那就是Angular的遍历指令，这个指令放在`<li>`元素上表示`<li>`元素和它的子元素是重复模板（repeater template）

>注意不要丢掉`*ngFor`前的星号，这是语法的重要组成部分。若需了解更多可到[模板语法]()章节。

注意到`NgFor`指令双引号内的`#hero`，这是模板本地变量声明，#号声明了一个本地变量，名为`hero`。

Angular会对列表里的每一项复制`<li>`元素，并使`hero`变量指向当前的遍历项（某个英雄），作为在双大括号插值的上下文。

>示例里`NgFor`恰巧是遍历数组，实际上，`NgFor`是可以操作任何可遍历的对象。

若`npm go`命令（这里没看懂，不是npm start么）还在运行中，此时我们应该能看到英雄列表了。

![英雄列表](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/3-hero-names-list.png)

## 创建数据类
当前我们是在组件里直接写死数据，作为示例展示并没什么大问题，但对于实际的实践中这不是一个好的写法。虽然在这个章节示例里我们不做处理，但我们会记下来，在未来的某个时间去修复处理。

当前的示例我们绑定的是字符串的数组，偶尔在实际应用中也会碰到，但大部分情况下我们需要展示的是一个对象，或是类的实例。

把之前的英雄名称的字符串数组转化为`Hero`对象数组，这时我们需要新建一个`Hero`类。
在`app/`文件夹里新建文件`hero.ts`，代码如下：

```Javascript
export class Hero {
  constructor(
    public id:number,
    public name:string) { }
}
```

我们已经定义了一个类，类的构造函数定义了两个属性：`id`和`name`。
如果我们是刚接触TypeScript，上面的代码看起来不像是属性定义，但实际上，我们已经定义了，这是TypeScript提供的新的属性声明的简便方式——参数属性。

请看第一个参数：

```Javascript
public id:number,
```

这种简洁语法同时：
- 声明了构造函数的参数和及其类型
- 声明了同名的公开访问的属性
- 用『new』实例化对象时，传入相应的参数也会同时赋值该公开访问属性

## 使用Hero类
让我们重新赋值`heroes`，使之成为Hero类的数组，同时重新以数组的第一个值赋值给`myHero`。

```Javascript
heroes = [
  new Hero(1, 'Windstorm'),
  new Hero(13, 'Bombasto'),
  new Hero(15, 'Magneta'),
  new Hero(20, 'Tornado')
];
myHero = this.heroes[0];
```

此时，我们需要更新模板，因为先前的`hero`是英雄名字符串，若不修改模板将会显示整个hero对象，所以需要将插值更改为`hero.name`。

```Javascript
template: `
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero.name}}</h2>
  <p>Heroes:</p>
  <ul>
    <li *ngFor="#hero of heroes">
      {{ hero.name }}
    </li>
  </ul>
`
```

示例的展示结果是一样的，但比之前的代码更好。

## 使用`NgIf`条件显示
有时需要满足某些特定的情况，App才展示一个视图或者是该视图的一部分。
修改一下我们的例子，当英雄数量很多时，就取超过3个吧，我们将展示一行消息。
`NgIf`指令会根据其值为`true`还是`false`，去插入或移除元素。通过在模板最后添加下面的片段，我们会看到效果。

```HTML
<p *ngIf="heroes.length > 3">There are many heroes!</p>
```

>注意不要丢掉`*ngIf`前的星号，这是语法的重要组成部分。若需要了解更多可到[模板语法]()章节。

在双引号里的模板语法看起来很像Javascript。当组件里定义的英雄数量超过3个，Angular就会插入这个片段到DOM里，消息就会显示出来。当英雄数量少于或等于3个，Angular会消去这个片段，消息就不会显示。

>Angular并不是显示和隐藏这条消息片段，而是从DOM里插入和移除片段元素。这一点很重要，如果我们需要处理大段的包含很多数据绑定的HTML代理，对性能会有很大的影响。

试一下，我们当前有4个英雄，所以那段消息是会显示出来的，回到`app.component.js`删除或注释掉其中一个英雄，浏览器会自动刷新，此时消息应该不会再显示出来了。

实践一下

## 总结
现在我们知道了

- 在双大括号内使用插值来显示组件属性
- 使用NgFor来显示数据列表
- 使用TypeScript的类在组件里去建立模型数据并显示之
- 使用NgIf根据布尔表达式选择性地显示HTML片段。

最终代码如下：
`app/app.component.ts`
```Javascript
import {Component} from 'angular2/core';
import {Hero} from './hero'
@Component({
  selector: 'my-app',
  template: `
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero.name}}</h2>
  <p>Heroes:</p>
  <ul>
    <li *ngFor="#hero of heroes">
      {{ hero.name }}
      </li>
  </ul>
  <p *ngIf="heroes.length > 3">There are many heroes!</p>
`
})
export class AppComponent {
  title = 'Tour of Heroes';
  heroes = [
    new Hero(1, 'Windstorm'),
    new Hero(13, 'Bombasto'),
    new Hero(15, 'Magneta'),
    new Hero(20, 'Tornado')
  ];
  myHero = this.heroes[0];
}
```
`app/hero.ts`
```Javascript
export class Hero {
  constructor(
    public id:number,
    public name:string) { }
}
```
`boot.ts`
```Javascript
import {bootstrap} from 'angular2/platform/browser';
import {AppComponent} from './app.component';
bootstrap(AppComponent);
```

下一步

除了数据显示，大部分的应用需要响应处理用户输入。请到[4. 用户输入](https://github.com/gf-rd/blog/issues/27)章节继续学习。

**Comment by F2EVarMan** [comment]
收获很多 赞

**Comment by YeaseonZhang** [comment]
NgIf条件显示：在双大

> **括号**

里的模板语法看起来很像Javascript。应该是

> **双引号**

**Comment by lizhonghui** [comment]
@YeaseonZhang 恩，多谢指出，已更正~

**Comment by YeaseonZhang** [comment]
@lizhonghui 翻译的很棒，感觉自己啃英文会吐^_^

**Comment by xz0** [comment]
大赞

**Comment by michaeltyhuang** [comment]
大赞！！

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
