### ISSUE TITLE
【Angular2开发指南】- 翻译系列总览【废弃】

### ISSUE THREAD

**Issue by lightningtgc** [gf-rd/blog#21]
## 【Angular2开发指南】- 翻译系列总览

>本系列翻译自 [Angular 2 Developer Guides](https://angular.io/docs/ts/latest/guide/)

>由【广发证券前端团队】倾情奉献

>多人众包翻译模式，如有不足之处，还望指出改进。

【Angular 2 开发者指南】是针对那些使用 `HTML`和 `JavaScript`构建客户端程序的有经验编程者的一个实用性的指南。

如果尚未入门 `Angular 2`的童鞋,可以参考官方[5分钟快速入门](https://angular.io/docs/ts/latest/quickstart.html),
对于想进一步了解 `Angular 2` 具体细节和常用使用的方法的童鞋可以继续阅读这个【Angular2 开发指南】。

#### 文章系列详情：
 - [1. Angular 备忘小抄 ](https://github.com/gf-rd/blog/issues/17)

 - [2. 架构综述](https://github.com/gf-rd/blog/issues/23)

 - [3. 数据显示](https://github.com/gf-rd/blog/issues/19)

 - [4. 用户输入](https://github.com/gf-rd/blog/issues/27)

 - [5. 表单](https://github.com/gf-rd/blog/issues/24)

 - [6. 依赖注入 ](https://github.com/gf-rd/blog/issues/12)   

 - [7. 模板语法](https://github.com/gf-rd/blog/issues/18)     

 - [8. 管道](https://github.com/gf-rd/blog/issues/16)

 - [9. 路由 & 导航](https://github.com/gf-rd/blog/issues/28)

 - [10. 生命周期钩子](https://github.com/gf-rd/blog/issues/13)

 - [11. 属性指令 ](https://github.com/gf-rd/blog/issues/22)

 - [12. 结构指令](https://github.com/gf-rd/blog/issues/14)

 - [13. 分级注入](https://github.com/gf-rd/blog/issues/25)

 - [14. 从1.x升级到2.0](https://github.com/gf-rd/blog/issues/15)

 - [15. 词汇表](https://github.com/gf-rd/blog/issues/26)

备注：这是2015年底翻译的成果，感谢大家的付出与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看

**Comment by ibufu** [comment]
感谢分享！

**Comment by jiayisheji** [comment]
感谢分享！

**Comment by mahuanhuan** [comment]
感谢分享！

**Comment by khahux** [comment]
thx

**Comment by juneszh** [comment]
Thx! 刚好昨天开始看NG2的文档研究NG1的项目如何升级, 有了翻译更轻松了

**Comment by iloveyo123u1** [comment]
thk

**Comment by shooterman** [comment]
Thx

**Comment by clijiac** [comment]
thx

**Comment by belowfrog** [comment]
奈斯

**Comment by alwayrun** [comment]
thx

**Comment by webappdevelp** [comment]
谢谢分享，必当好好阅读和实践

**Comment by qingniao99** [comment]
6666666666666666

**Comment by kop-still** [comment]
thx

**Comment by kittencup** [comment]
已添加进 https://github.com/kittencup/angular2-learning-cn

大家如果有angular 2问题 可以来 https://github.com/kittencup/angular2-ama-cn 提问

**Comment by dlanan2k** [comment]
感谢!

**Comment by jeremyjy** [comment]
thx for sharing

**Comment by JulyXing** [comment]
辛苦了，谢谢分享。

**Comment by savokiss** [comment]
thks!!

**Comment by kornhill** [comment]
excellent，译的好。

**Comment by xiongxin** [comment]
有兴趣翻译dart版的吗？正在学习dart版ng2

**Comment by Drupaloops** [comment]
thx

**Comment by fengchuantao** [comment]
good

**Comment by jinges** [comment]
mark

**Comment by zhailei31665431** [comment]
感谢分享。

**Comment by fingerart** [comment]
thank you !

**Comment by afeng0007** [comment]
thank you !

**Comment by dawanraoming** [comment]
感谢分享。

**Comment by Shyam-Chen** [comment]
官網有新的章節 Http Client

**Comment by helloyxw** [comment]
http client 章节有人翻译吗，贡献一下呗

**Comment by lightningtgc** [comment]
@Shyam-Chen 感谢提醒！
@helloyxw 已在翻译中，因工作缘故，近期会再次更新

谢谢支持

**Comment by tolbkni** [comment]
mark

**Comment by zhouyupeng** [comment]
mark

**Comment by alwayrun** [comment]
![image](https://cloud.githubusercontent.com/assets/558808/14939457/702c0ea2-0f7a-11e6-9169-2f7f37f31ec5.png)
这里有一个Angular2的微信群

**Comment by mlyknown** [comment]
mark

**Comment by richdyang** [comment]
这就是翻译官方的文档嘛，我以为会有什么干货。况且现在都rc2了，其中form, router都改了不要太多，基本这份文档也过时了
