### ISSUE TITLE
【Angular2开发指南】11. 属性指令

### ISSUE THREAD

**Issue by qhf** [gf-rd/blog#22]
# <a name="title"/>属性指令
 属性指令（Attribute directives）可以为DOM元素添加动作行为。

**属性**指令能够改变指定DOM元素的外观或行为。

在这一章中，我们将
* 编写一个属性指令来改变背景颜色
* 对模板中的DOM元素应用属性指令
* 响应处理用户触发事件
* 使用数据绑定方式传值给指令

[在线示例](https://angular.io/resources/live-examples/attribute-directives/ts/plnkr.html)
  
## <a name="directives-overview"/>指令概述
在Angular中，包含有以下三种类型的指令：
 1. 组件
 2. 结构指令  
 3. 属性指令
 
*组件*是一种真正包含模板的指令，它也是应用程序开发时三种指令中最常见、使用最多的指令。

[*结构*指令](https://github.com/gf-rd/blog/issues/14)用来添加/移除DOM元素，以改变DOM布局。[NgFor](https://github.com/gf-rd/blog/issues/18#ngfor) 和 [NgIf](https://github.com/gf-rd/blog/issues/18#ngif) 是两种常见的结构指令。
  
*属性*指令用来改变DOM元素的外观和行为。比如Angular内置的 [NgStyle](https://github.com/gf-rd/blog/issues/18#ngstyle) 指令，能够同时改变一个DOM元素的多种样式。
  
接下来我们将自己编写一个属性指令，实现当用户鼠标停留在DOM元素上时，改变该DOM元素的背景颜色。
 > 虽然我们可以也不用任何指令，通过下面这种[样式绑定](https://github.com/gf-rd/blog/issues/18#style-binding)方式就能够设置背景颜色：
 > ```
 > <p [style.background]="'lime'">I am green with envy!</p>
 > ```
 > 但这样就失去了自己编写指令的乐趣。
 > 而且，我们不只是要简单*设置*背景颜色，而是要做到，当用户鼠标悬停时，动态地*改变*背景颜色。仅靠[样式绑定](https://github.com/gf-rd/blog/issues/18#style-binding)方式是难以实现这一功能的。

## <a name="build-a-simple-attribute-directive"/>编写一个简单的属性指令
一个属性指令至少需要一个控制器类，该控制器类使用`Directive` 装饰器来注解。`Directive` 装饰器指定了用以标记指令所关联属性的选择器，控制器类则实现了指令所对应的特定行为。
 
现在我们创建一个例子来说明。

### <a name="our-first-draft"/>初步版本

首先创建一个新的工程目录(`attribute-directives`) ，按照[入门指南](https://angular.io/docs/ts/latest/guide/../quickstart.html)中指示的步骤操作。
  
在`app` 文件夹中新建一个文件，叫做`highlight.directive.ts` ，添加如下代码：
```javascript
import {Directive, ElementRef, Renderer, Input} from 'angular2/core';

@Directive({
    selector: '[myHighlight]'
})

export class HighlightDirective {
    constructor(el: ElementRef, renderer: Renderer) {
        //el.nativeElement.style.backgroundColor = 'yellow';
	       renderer.setElementStyle(el, 'backgroundColor', 'yellow');
	    }
	}
```

先从Angular库中导入一些标记符号，使用 `Directive` 符号来标记`@Directive` 装饰器，使用*Element Reference* （元素引用）和 *Renderer*（渲染器）符号来作为[依赖注入](https://github.com/gf-rd/blog/issues/12)到指令的构造函数中。暂时不需要用到`Input`符号，我们在后面中才将用到。

然后在一个配置对象中定义指令的元数据，作为参数传递给 `@Directive` 装饰器函数。`@Directive`装饰器使用一个CSS选择器来识别该属性指令所关联的HTML模板。[CSS属性选择器](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)是指方括号中描述的属性名。
 
从上面代码看出，`[myHighlight]`是我们编写的指令所对应的选择器 。当指令运行时，Angular会在模板中匹配找到所有包含属性名称叫做`myHighlight`的DOM元素。
>### <a name="why-not-call-it-highlight-"/>为什么不叫 “highlight”？
>*highlight* 是一个比*myHighlight*更好听的名字，而且技术上同样也起作用。
>
>但是，我们推荐使用有连字符的选择器名称，避免跟HTML标准属性名称冲突。如果我们使用了一个自己的选择器前缀，这样也大大降低与第三方指令名称冲突的可能性。
>
>我们不能使用`ng`作为`highlight`指令的前缀，因为`ng`是Angular的官方前缀，使用`ng`前缀的话会把自己的指令与官方指令混淆在一起。
>
>因此，在本文中，我们使用了`my`作为指令名字前缀，使用起来也简短方便。
 
在声明 `@Directive` 这个元数据后，我们导出了指令的控制器类，方便被其他组件访问。该控制器类实现了指令所包含的逻辑。

Angular会为每一个匹配的DOM元素创建了一个控制器类实例，同时将 *Element Reference* 和 *Renderer* 服务作为参数传递给实例构造函数。我们将使用这些*服务* 来设置DOM元素的背景颜色。 

本章的代码演示了设置颜色的两种方法。
  
第一种方法是，通过访问DOM元素引用的 `nativeElement` 属性，调用浏览器标准DOM API来设置元素的背景颜色。这种方法就不需要用到 `Renderer` 服务。

我们不提倡使用这种方法，也不喜欢用它，我们更加倾向于使用第二种方法，即基于`Renderer` 服务实现DOM元素属性的设置。

>### <a name="why-prefer-the-renderer-"/>为什么Renderer服务是更好地选择?
>直接操作DOM是一种我们尽量*避免*的做法，因为这样会把我们束缚在了DOM API的限制内。
>
> `Renderer`服务可以让我们脱离了DOM API的限制，而且增加了灵活性，比如它能在渲染阶段运行在一个Web Woker中，从而达到更快的性能。同时，`Renderer`服务也支持指令运行在一个非浏览器环境中，比如服务端渲染。服务端渲染能提高页面的运行效率，也对搜索引擎SEO友好。

## <a name="apply-the-attribute-directive"/>应用属性指令
我们即将编写`AppComponent`应用，用来演示上面编写的`HighlightDirective` 指令的使用。首先，让我们先创建一个新HTML内容模板，将指令作为一个属性应用到`span`元素上。用Angular术语来说，这个`span`元素是属性指令的**宿主**。

把下面的html内容写入到`app.component.html` 文件中：
```html
<h1>My First Attribute Directive</h1>
<span myHighlight>Highlight me!</span>
```

这是一个只有两行代码的模板，看起来有点过了。但这样也有利于后面对这个模板内容进行扩展补充。同时，也方便`AppComponent` 快速引用该模板。
```javascript
import {Component} from 'angular2/core';
import {HighlightDirective} from './highlight.directive'
@Component({
  selector: 'my-app',
  templateUrl: 'app/app.component.html',
  directives: [HighlightDirective]
})
export class AppComponent { }
```

在上面代码中，我们添加一个 `import` 声明，以导入`Highlight`指令类，并将该指令类添加到组件元数据的`指令`数组中。当Angular在HTML模板中碰到`myHighlight`属性时，就能识别找到对应的`Highlight`指令。否则，Angular会忽略掉`myHighlight`属性的处理。
 
运行整个示例程序后，便能看到，span文本被我们所编写的指令高亮背景色了：  

  ![First Highlight](https://angular.io/resources/images/devguide/attribute-directives/first-highlight.png)

让我们来回顾一下工作原理：

Angular在`<span>`元素上解析到元素包含有`myHighlight`属性后，创建了属性对应的`HighlightDirective`指令类的一个实例，将元素和`Renderer`服务引用作为参数传给该实例构造函数，构造函数内部调用了`Renderer`服务，将`<span>`元素的背景颜色设为黄色。

## <a name="respond-to-user-action"/>处理响应用户动作

我们并不满足于简单设置元素的颜色。我们编写的指令还可以根据用户动作来设置颜色。比如说，当用户将鼠标停留在元素上时，动态改变元素的颜色。

为实现这一功能 ，我们将需要做到：
 1. 检测用户鼠标移进/移出元素事件；
 2. 响应用户事件，设置/清除高亮颜色。
  
开始事件检测。我们在指令元数据中添加一个`host` 属性，在属性配置对象声明了两个鼠标事件以及事件发生时所触发的指令方法。
```javascript
host: {
  '(mouseenter)': 'onMouseEnter()',
  '(mouseleave)': 'onMouseLeave()'
}
```

>`host` 属性指的是作为属性指令宿主的DOM元素，在我们的例子中也就是`<span>`元素。 
> 
> 我们也可以使用普通avaScript对象，直接为原生元素（`el.nativeElement`）添加事件监听器。但这样至少存在三种问题：
>	  1. 必须正确地编写监听器。
>	  2. 必须在指令销毁后*移除*监听器，避免内存泄露。
>	  3.  会直接操作DOM API，但这正是上面我们所说的需要避免的方式。
>
 > 因此，我们还是回到使用 `host` 属性声明方式上。

现在我们实现这两个鼠标事件的处理函数： 
```javascript
onMouseEnter() { this._highlight("yellow"); }
onMouseLeave() { this._highlight(null); }

private _highlight(color: string) {
  this.renderer.setElementStyle(this.el, 'backgroundColor', color);
}
```

请注意到处理函数使用了一个辅助类方法来调用`Renderer` 服务，调用方式跟在构造函数中的用法一致。

虽然我们已不需要实现构造函数内部代码，但仍旧需要注入 `ElementRef` 和`Renderer` 服务。可以通过修改构造函数签名来捕获注入私有变量的服务示例，然后清空构造函数内部实现。
```javascript
constructor(private el: ElementRef, private renderer: Renderer) {
}
```

更新后的指令代码，如下所示：
```javascript
import {Directive, ElementRef, Renderer, Input} from 'angular2/core';
@Directive({
  selector: '[myHighlight]',
  host: {
    '(mouseenter)': 'onMouseEnter()',
    '(mouseleave)': 'onMouseLeave()'
  }
})
export class HighlightDirective {
  constructor(private el: ElementRef, private renderer: Renderer) {
  }
  onMouseEnter() { this._highlight("yellow"); }
  onMouseLeave() { this._highlight(null); }
  private _highlight(color: string) {
    this.renderer.setElementStyle(this.el, 'backgroundColor', color);
  }
}
```

运行应用程序后，可以确认当用户鼠标移到`span`元素上时，背景颜色显示成所指定的颜色，当鼠标移走后，背景颜色便消失了。
![Second Highlight](http://angular.io/resources/images/devguide/attribute-directives/highlight-directive-anim.gif)

## <a name="configure-the-directive-with-binding"/>使用绑定方式配置指令
当前指令是硬编码声明高亮颜色的，这意味着颜色不能灵活改变。我们可以采用另外一种方式，使用绑定方式在指令外部设置高亮颜色，如下：
```html
<p [myHighlight]="color">Highlight me!</p>
```

接下来，我们将扩展指令类，为它实现一个可绑定**输入**的`highlightColor`属性，使用这个属性来高亮文本。

这是指令类的最终版本：
```javascript
export class HighlightDirective {
  @Input('myHighlight') highlightColor: string;
  private _defaultColor = 'red';
  constructor(private el: ElementRef, private renderer: Renderer) { }
  onMouseEnter() { this._highlight(this.highlightColor || this._defaultColor); }
  onMouseLeave() { this._highlight(null); }
  private _highlight(color:string) {
    this.renderer.setElementStyle(this.el, 'backgroundColor', color);
  }
}
```

新提供的 `highlightColor` 属性是一个“input”（输入）属性，也就是数据从绑定表达式流向输入到指令中。请注意到，我们定义这种类型属性时，要调用到`@Input()`装饰器函数。
```
@Input('myHighlight') highlightColor: string;
```

`@Input()`装饰器添加元数据到指令类中，使`highlightColor` 属性具有属性绑定能力，并通过`myHighlight` 别名体现出来。这种input元数据声明是必不可少的，否则Angular将会拒绝为该属性添加绑定能力。

后面的[附录](#why-input)解释了原因： 
>开发者使用指令时，希望绑定的属性名称是`myHighlight`。但指令的属性名称是 `highlightColor`。这两者是不一致的。
>
>为了避免这种矛盾，我们可以将属性命名为 `myHighlight` ：
>```javascript
>@Input() myHighlight: string;
>```
>
>将属性名字写在指令内部，这也许不符合我们的想法。我们可以将`myHighlight` 传给`@Input` 装饰器，作为`highlightColor`属性的别名：
>```javascript
>@Input('myHighlight') highlightColor: string;
>```

现在，高亮颜色已经能够作为一种输入，我们便可以修改 `onMouseEnter()` 方法来引用高亮颜色，从而替换原来的硬编码方式。还可以定义一种默认的红色，作为默认绑定颜色。
```javascript
onMouseEnter() { this._highlight(this.highlightColor || this._defaultColor); }
```

现在，更新我们的`AppComponent` 模板代码，让用户可以选择绑定到指令的高亮颜色。

这是更新后的模板代码:
```html
<h1>My First Attribute Directive</h1>
<h4>Pick a highlight color</h4>
<div>
  <input type="radio" name="colors" (click)="color='lightgreen'">Green
  <input type="radio" name="colors" (click)="color='yellow'">Yellow
  <input type="radio" name="colors" (click)="color='cyan'">Cyan
</div>
<p [myHighlight]="color">Highlight me!</p>
```

>### <a name="where-is-the-templated-color-property-"/>模板中的“color”属性指什么?
>
>眼尖的同学会注意到，模板中的单选按钮点击事件处理器设置了一个绑定给指令的`color` 属性。按理，我们应该在宿主应用程序 `AppComponent`中会找到具体的`color`代码。 
>
>**从上面看出，我们并没有在*AppComponent*应用中定义color属性**！ 但是这段代码能运行起来。因此，模板中的`color`值从哪里来?
>
>通过浏览器的调试功能发现，Angular为`AppComponent` 运行实例动态添加了一个 `color` 属性。
>
>这是一种*便捷*的方式，但同样也是一种令人困惑的*隐晦*行为。 虽然这种技术看起来比较酷，我们还是推荐在 `AppComponent` 中手工添加`color` 属性。

这是我们编写的指令第二版：

![Highlight v.2](https://angular.io/resources/images/devguide/attribute-directives/highlight-directive-v2-anim.gif)

## <a name="bind-to-a-second-property"/>绑定两个属性
我们编写的指令目前只有一个可定制的属性，是否能定义***两个这样的属性***呢？
  
让我们给模板设置默认的颜色， 一直到用户点击选择后才切换高亮颜色。然后我们给`HighlightDirective`指令添加第二个**input**属性，叫做`defaultColor`:
```javascript
@Input() set defaultColor(colorName:string){
  this._defaultColor = colorName || this._defaultColor;
}
```

`defaultColor` 属性具有一个setter，支持重写覆盖掉默认的硬编码颜色（红色）。这里我们不需要实现getter。

我们已经将`myHighlight`属性显式声明为一个可绑定对象，接下来怎么将它与`defaultColor` 属性绑定？

请记住， *组件也是一种指令*。 我们能够在模板中为组建添加任意多的属性绑定，例如下面的例子，将`a`、 `b`、`c` 属性分别绑定了`a`、 `b`、`c` 字符串值：
```html
<my-component [a]="'a'" [b]="'b'" [c]="'c'"><my-component>
```

同样的做法也适用于属性指令：
```html
<p [myHighlight]="color" [defaultColor]="'violet'">
  Highlight me too!
</p>
```

上面例子中，我们将用户选定的颜色绑定给了前面声明的`myHighlight` 属性。同时也将字符串描述的'violet'颜色绑定给了`defaultColor` 属性。

这是我们编写的指令最终版本：    
![Final Highlight](https://angular.io/resources/images/devguide/attribute-directives/highlight-directive-final-anim.gif)

## <a name="summary"/>总结

现在，我们已经掌握了（怎样）：
 - 构建一个简单的**属性指令**，为DOM元素添加动作；
 - 在模板中使用指令；
 - 响应**用户事件**，在事件中处理逻辑；
 - 使用**绑定**方式传值给属性指令。

最终的代码示例如下：

**app.component.ts:**
```javascript
import {Component} from 'angular2/core';
import {HighlightDirective} from './highlight.directive'
@Component({
  selector: 'my-app',
  templateUrl: 'app/app.component.html',
  directives: [HighlightDirective]
})
export class AppComponent { }
```

**app.component.html:**
```html
<h1>My First Attribute Directive</h1>
<h4>Pick a highlight color</h4>
<div>
  <input type="radio" name="colors" (click)="color='lightgreen'">Green
  <input type="radio" name="colors" (click)="color='yellow'">Yellow
  <input type="radio" name="colors" (click)="color='cyan'">Cyan
</div>
<p [myHighlight]="color">Highlight me!</p>
<p [myHighlight]="color" [defaultColor]="'violet'">
  Highlight me too!
</p>
```

**highlight.directive.ts:**
```javascript
import {Directive, ElementRef, Renderer, Input} from 'angular2/core';
@Directive({
  selector: '[myHighlight]',
  host: {
    '(mouseenter)': 'onMouseEnter()',
    '(mouseleave)': 'onMouseLeave()'
  }
})
export class HighlightDirective {
  @Input('myHighlight') highlightColor: string;
  private _defaultColor = 'red';
  @Input() set defaultColor(colorName:string){
    this._defaultColor = colorName || this._defaultColor;
  }
  constructor(private el: ElementRef, private renderer: Renderer) { }
  onMouseEnter() { this._highlight(this.highlightColor || this._defaultColor); }
  onMouseLeave() { this._highlight(null); }
  private _highlight(color:string) {
    this.renderer.setElementStyle(this.el, 'backgroundColor', color);
  }
}
```

**boot.ts:**
```javascript
import {bootstrap}    from 'angular2/platform/browser'
import {AppComponent} from './app.component';
bootstrap(AppComponent);
```

**index.html:**
```html
<!DOCTYPE html>
<html>
<head>
  <title>Attribute Directives</title>
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script>
      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
    </script>
</head>
<body>
  <my-app>loading...</my-app>
</body>
</html>
```
<a id="why-input"></a>
### <a name="appendix-input-properties"/>附录: Input属性
  
在本文前面，我们将 `highlightColor` 属性声明为`HighlightDirective`指令的一个***input***属性。

之前用于绑定的属性，我们并没有做什么声明。为什么现在需要？
  
因为Angular对绑定的**源**和**目标**确立了一个微妙但重要的区别。

在之前的所有绑定中，指令或组件属性都是作为一个绑定**源**。如果一个属性在模板表达式显示在=号***右边***，则该属性是一个绑定**源**。
  
如果一个属性显示在=号***左边***，则该属性是绑定**目标**，例如`HighlightDirective`指令中的 `myHighlight`属性：
```html
<p [myHighlight]="color">Highlight me!</p>
```

上面的代码示例中，`[myHighlight]="color"` 表达式中的 'color' 是一个绑定**源**。绑定**源**属性不需要声明定义。

而表达式中的'myHighlight' 则是一个绑定**目标**。我们必须将这种属性声明为 *input* 属性。否则Angular会认为是一个明显错误，从而使绑定失效。 
  
Angular对绑定*目标*属性进行区别对待，这是一种很好的做法。当组件或指令处于目标位置时，需要得到一定的保护。

想象一下，我们的`HighlightDirective`指令没有神奇魔法技巧，但也是一种优雅地实现。
  
有些人天真地以为，可以将绑定应用到指令的每个属性上。不只是一两个属性，而是*每一个*属性。这样便会让指令运行变得一团糟，运行结果难以预料。幸好地，我们没有用到也不希望用到种方式。
  
*input*声明方式可以保证指令使用者，只能将属性绑定到公有API上，除此之外都不能绑定。

>### 下一章
>[12. 结构指令](https://github.com/gf-rd/blog/issues/14)

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
