### ISSUE TITLE
【Angular2开发指南】5、表单

### ISSUE THREAD

**Issue by coyuanye** [gf-rd/blog#24]
示例代码以TypeScript为例

表单可以是紧密结合的，有效的，令人信服的数据录入。一个angular表单可以实现用户控制，监视变化，验证输入和错误信息处理，数据绑定等功能。

我们经常使用表单来实现登录，寻找帮助，下订单，订机票，安排会议和执行数不胜数的其他数据任务。表单是商务应用的支柱。

任何经验丰富的web开发人员能够直接使用正确的标签完成一个html表单。创建一个集成可以暗中高效并且有效引导用户数据录入的表单具有挑战性。

这章就主要是讨论这方面的技巧。

这章我们也将探讨angular表单关于双向绑定，实时监视，有效性检测和出错处理的支持。

接下来我们将创建一个简单的表单，每次一个步骤。并按如下步骤来学习：
* 如何用一个组件和模板来创建一个angular表单
* ngModel双向数据绑定的读写语法和在input中的值
* ngControl指令监视表单的变化状态和数据有效性检测
* ngControl添加给表单的特殊的CSS类，并用该如何使用这些类来提供明显的可视效果
* 如何向用户展示错误信息和激活/禁用表单
* 如何通过控制模板局部变量来展示信息

## 模板驱动表单

大多数人会通过使用带有表单特殊指令和这章描述的技术的angular模板语法书写模板来创建表单。

> 这不是唯一的方式去创建一个表单但这将是我们这一章的方式

使用angular的模板我们几乎可以创建任何一个我们需要的表单—登录表单、联系表单…几乎所有的商务表单。我们可以创造性的使用，为他们绑定数据，特殊的校验规则和展示错误信息，条件性的激活/开启控制，触发内置的可视效果，甚至更多功能。

由于angular处理了很多重复的任务，并有示例，这样我们用起来将会相当容易，否则我们将会处理这些苦恼的事情

我们将会探讨并且学习如何创建一个下面这种模板驱动型表单：

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-hero-form-1.png)

在英雄代理机构我们用这个表单来维护关于英雄的个人信息。每一个英雄需要一份职责。我们公司的使命就是将英雄匹配到正确的任务。

这个表单中的三处有两处是需要必填的。必填的区域在左侧有一个绿色的边条已使他们很容易被认出。

如果删掉了英雄的名字，该处将会用一种引人注目的样式来提示出错了。

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-hero-form-2.png)

表单的提交按钮将会禁用并且左侧的边条也会从绿色变为红色。

> 我们可以用标准的CSS来定制边条的颜色和位置。

我们将按照下面的步骤来创建这个表单：

1. 创建一个Hero模型
2. 创建控制表单的组件
3. 用最初的表单布局来创建一个模板
4. 为每一个表单控件添加ngModel指令
5. 为每一个表单控件添加ngControl指令
6. 添加定制的CSS来提供可视效果
7. 显示和隐藏错误信息
8. 用ngSubmit来控制表单的提交
9. 在表单有效之前禁用表单的提交按钮

### 架构

创建一个新的项目文件夹（angular2-forms），然后按照[快速开始](https://angular.io/docs/ts/latest/quickstart.html)的步骤进行设置。

### 创建Hero模型

作为用户输入表单的数据，我们需要捕获数据的变化并且更新模型的实例。直到我们知道这个模型看起来像什么的时候我们才能设置这个表单。

一个模型能够像一个“属性标签”那么简单用来说明一个应用的重要性。用三个必填的控件（id, name, power）和一个可选的控件（alterEgo）能够很好的描述我们的Hero类。

在app文件夹创建一个叫做hero.ts的文件，代码如下：

```Javascript
export class Hero {
    constructor(
        public id:number,
        public name:string,
        public power:string,
        public alterEgo?:string){}
}
```

这是一个没有要求和表现的低能模型。但是作为我们的例子却非常合适。

当我们创建新的英雄的时候TypeScript编译器会为每一个公共的构造函数参数创建一个公共的区域并且自动的分配这个参数的值到那个区域。

当构造器省略alterEgo时alterEgo是可选的。在alterEgo?里标记(?)。

我们可以像这样创建一个新的英雄：

```
let myHero = new Hero(42,’SkyDog’,’Fetch any object at any distance’,’Leslie Rollover’);
console.log(‘My hero is called ’ + myHero.name); //”My hero is called SkyDog”
```

## 创建表单组件

一个angular表单由两部分组成：一个基于HTML的模板和一个基于code的控制数据和用户交互的组件。

以组件开始是因为它能够简单的确定Hero编辑者能做什么。

创建一个新的叫做hero-form.compontern.ts的文件，代码如下：

```Javascript
import {Compontent} from ‘angular2/core’;
import {NgForm} from ‘angular2/common’;
import {Hero} from ‘./hero’;
@Component ({
    selector: ‘hero-form’, 
    templatrUrl: ‘app/hero-form.compontent.html
})
export class HeroFormCompent {
    powers = [‘ReallySmart’,’Super Flexible’,’Super Hot’,’Weather Changer’];
    model=new Hero(18,’DrIQ’,this.powers[0],’Chuck Overstreet’);
    submitted = false;
    onSubmitt(){this.submitted= true;}
    //TODO:Remove this when we’re done get diagnostic(){return JSON.stringify(this.model);}}
```

这个组件没什么特别，和我们之前写过的组件没什么区别。

 理解这个组件仅仅需要我们前面章节学过的概念。

1. 像我们经常做的那样从angular引入Component。
2. 值为”hero-form”的@Component选择器意味着我们能够在父模板用一个<hero-form>的标签结束表单。
3. templateUrl属性指向一个叫做hero-form.component.html的HTML模板
4. 我们为model和powers定义虚拟数据用于演示。如此这般，我们能够通过注入数据服务来获取和存储真正的数据或者可能揭露这些作为为父组件绑定的输入输出。现在不必担心，将来改变也不会影响表单。
5. 最后我们把model返回的JSON丢进diagnostic的属性里。这将帮助我们看到在我们的开发期间所做的事情；它们自己将会清理并且稍后丢弃。

为什么我们不将模板写到组件文件就像我们经常在其他开发指南做的那样？

 

没有正确的答案来回答所有的场合。当模板比较短的时候我们喜欢使用内联模板。大多数的表单模板不是短的。Typescript和JavaScript文件通常不是读写HTML最好的地方并且很少程序员会喜欢一个HTML和代码混合的文件有帮助。我们也喜欢像这个具有清晰明确目的的短文件。

我们有另外一个其他的加入HTML模板的好的选择。立刻写那个模板。在我们这么做之前，我们将回退一步，修改app.component.ts文件来使用我们新的HeroFormComponent。

### 修改app.component.ts

app.component.ts是这个应用的根组件。它将控制我们的新HeroFormComponent。

替换“快速开始”版本里面的内容如下：

```Javascript
import {Component} from ‘angular2/core’;
import {HeroFormComponent} from ‘./hero-form.component’
 
@Component({
    selector: ‘my-app’, 
    template: ‘<hero-form></hero-form>’, 
    directives: [HeroFormComponent]
})
 
export class AppComponent{}
```

> 仅仅有三个改变：
1. 我们引入了新的HeroFormComponent。
2. 模板是用组件的selector属性定义的简单的新标签。
3. 指令数组告诉angular模板依赖于自身也是指令的HeroFormComponent（和所有的组件一样）。

### 初始化一个表单模板

初始化一个叫做hero-form.component.html的模板，代码如下：

```Html
<div class=”container”>
    <h1>Hero Form</h1>
    <form>
        <div class=”form-group”>
            <lable for=”name”>Name</lable>
            <input type=”text” class=”form-control” required>
        </div>
        <div class=”form-group”>
            <lable for=”alterEgo”>Alter Ego</lable>
            <input type=”text” class=”form-control”>
        </div>
        <button type=”submit” class=”btn btn-default”>Submit</button>
    </form>
</div>
```

这是一个普通的HTML5.我们放置了两个Hero控件，name和alterEgo，并且在输入框里为用户开放允许输入。

 

Name控件具有HTML5的必填项属性；Alter Ego控件没有是因为alterEgo是选填的。

最后放置了一个具有一些class的提交按钮。

目前我们还没有使用angular。没有绑定数据。没有指令。仅仅是布局。

container,form-group,form-control和btn样式纯粹来自于Twitter Boostrap。使用Bootstrap来打扮表单。嘿，没有任何样式的表单会是什么样！

> Angular表单没有自己的样式库
Angular自身没有使用container,form-group,form-control和btn类名或者任何的外部库。Angular应用可以使用任何css库，或者都不使用。

添加样式的方法：

1. 在应用的根目录打开一个终端窗口，输入：npm install bootstrap –save。
2. 打开index.html，在head里面添加链接：<link rel=”stylesheet” href=”node_modules/bootstrap/dist/css/bootstrap.min.css”。

### 添加带有*ngFor的power

英雄可能从一个机构批准的功能列表里面选择一个超级功能。我们本质地保持列表不变（在HeroFormComponent里）。

为表单添加一个下拉框并且使用NgFor绑定参数到powers列表，一种我们可能在数据显示章之前学到的技术。

添加下面的html在Alter Ego下面。

```Html
<div class=”form-group”>
 
    <label for=”power”>Hero Power</label>
    <select class=”form-control” required>
        <option *ngFor=”#p of powers” [value]=”p”>{{p}}</option>
    </select>
</div>
```

我们为功能列表里面的每一个功能重复一次<options>标签。#q模板局部变量在每一次迭代中代表不同的功能；我们用双大括号的插值法语法来展示它的名字。

## 使用*ngModel双向绑定数据

立刻运行这个应用将会显示如下

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-hero-form-3.png)

我们没能看到hero数据是因为我们还没有为Hero绑定数据。在之前的章节数据显示中我们已经知道该如何去操作了, 用户输入告诉了我们如何使用一个事件绑定来监听DOM事件和如何使用一个显示的值来更新组件属性。

现在我们需要在同一时间去显示、监听和摘录数据。

我们本可以在表单中再一次使用这些技术。取而代之的是我们将介绍一些新的技术，NgModel指令可以令表单和模型的数据绑定超级简单。

找到Name的输入框并且像这样去更新代码。app/hero-form.commonent.html(节选)

```Html
<input type=”text” class=”form-controt” required [(ngModel)]=”model.name”>TODO:移除这个{{model.name}}
```

> 在input标签后追加了一个插值这样我们能够看到我们在做什么。当我们完成后留下了一个笔记。

注意绑定语法：[(ngModel)]=”…”。

如果立刻运行应用并且开始在Name输入框里输入值，添加和删除值，将会看到这些值从插入的文字中出现和消失。某一瞬间看起来像这样：

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-ng-model-in-action.png)

测试结果说明文字确实按照输入框里面的值发生变化，反过来也是。这就是双向数据绑定。

让我们为Alter Ego和Hero Power添加类似于[(ngModel)]的绑定。我们将抛弃输入框的信息并且在这个组件的头部添加一个新的绑定属性diagnostic。然后就能确认双向数据绑定为每一个Hero模型起作用。

修改后的表单将会有三处[(ngModel)]绑定，看起来像这样：app/hero-form.commonent.html(节选)

```Html
{{diagnostic}}
<div class=”form-group”>
    <label for=”name”>Name</label>
    <input type=”text” class=”form-control” required [(ngModel)]=”model.name”>
</div>
<div class=”form-group”>
    <label for=”alterEgo”>Alter Ego</label>
    <input type=”text” class=”form-control” [(ngModel)]=”model.alterEgo”>
</div>
<div class=”form-group”>
    <label for=”power”>Hero Power</label>
    <select class=”form-control” required [(ngModel)]=”model.power”>
        <option *ngFor=”#p of powers” [value]=”p”>{{p}}</option>
    </select>
</div>
```

现在运行应用并改变每一个Hero的模型属性，将可能会看到这种想象：

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-ng-model-in-action-2.png)

在表单头部的diagnostic确认了所有的改变都会反应在模型中。

删除头部的{{ diagnostic }}绑定因为它已经达到了展示的目的。

> [(ngModel)]原理
这部分是深入[(ngModel)]的可选部分，不感兴趣的，可以越过。
在绑定语法里的标点符号[()]是一个很好的预示将会发生什么的线索。
在绑定属性里，值产生于模型赋予给目标属性。我们通过环绕他名字周围的括号—[]来辨认那个目标属性。这是一种模型向视图的单向数据绑定。
在事件绑定中，产生于目标属性的值赋予给模型。我们通过环绕让名字周围的括号—()来辨认那个目标属性。这是一种反向的视图向模型的单向数据绑定。
不用惊讶angular会选择混合使用[()]这种标点符号来表示双向数据绑定并且数据双向。
实际上，我们能够将ngModel打断为绑定在它的两个独立的模式中，就像我们改写“Name”控件绑定那样：app/hero-form.commonent.html(节选)
```Html
<input type=”text” class=”form-control” required [ngModel]=”model.name” (ngModelChange)=”model.name=$event”>TODO:remove this: {{model.name}}
```
绑定属性有一种熟悉的感觉。事件绑定看起来奇怪一些。
ngModelChange不是一个input元素事件。实际上它是NgModel指令的一个事件属性。当angular在表单中看到一个绑定目标[(abc)]时，它希望这个abc指令拥有一个abc的输入属性和一个abc-change的输出属性。
另一个怪事是这种模板表达式：model.name=$event。我们使用它来发现来自于DOM事件的$event对象。ngModelChange属性不会产生一个DOM事件；它是能够返回输入框的一种angular的EventEmitter属性，这种属性能够精确的捕获我们分配给模型”name”属性的值。
很高兴的知道了但是这个有用吗？我们多数情况下更喜欢用[(ngModel)]。如果必须在事件处理中去做一些特殊的事情比如键盘的冒泡或节流时我们可能分离他们。
在模板语法章节中可以学到更多关于NgModel和其他模板语法的知识。

### 用ngControl监视改变状态和有效性监测
 
表单不仅仅是数据绑定。我们同样希望我们控制表单的状态。NgControl指令会保持对状态的监视。

>ngControl需要在表单中使用
NgControl是NgForm指令家族的一员，仅仅能够用于form标签。

如果用户触发了控制器，值发生了变化或者值变得无效了我们的应用能够唤起NgControl。

NgControl不仅仅监视状态改变；它能用上面我们设置的特殊的angular CSS类更新控制器。我们能够通过影响这些类名来改变控制器并使信息出现或者消失。

我们能够瞬间探测到这些影响。现在我们马上为表单的三个控件添加ngControl，并使用控件的名称。
app/hero-form.commonent.html(节选)

```Html
<input type=”text” class=”form-control” required [(ngModel)]=”model.name” ngControl=”name”>
```

确保为每一个ngControl指令分配了一个唯一的名字。

>Angular用NgForm的ngControl名字注册控制器。我们不需要特别的添加NgForm指令，但是在[下一章](https://angular.io/docs/ts/latest/guide/dependency-injection.html)我们将会讨论它。

### 为可视效果添加定制的CSS

NgControl不仅仅监视状态。它会在这三个影响状态的方面更新控制器。

状态 | 如果Class为True |如果Class为False
------- | ----- |-------
控制器被访问  | ng-touched | ng-untouched
控制器被访问 | ng-untouched | ng-untouched
控制器的值是有效地 | ng-untouched | ng-invalid

现在为“Name”的控件添加一个叫做spy的临时的模板局部变量并用spy来展示这些样式。
app/hero-form.commonent.html(节选)

```Html
<input type=”text” class=”form-control” required [(ngModel)]=”model.name” ngControl=”name” #spy>
<br>TODO: remove this {{spy.className}}
```

现在运行这个应用并且聚焦到这个Name控件上。准确的按照下面的四个步骤操作：

1. 看但是不要触碰
2. 单击输入框，然后单击输入框的外部
3. 在名字的后面添加斜线
4. 擦除名字

动作和效果如下所示：
![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-control-state-transitions-anim.gif)

我们能够看到下面的四个步骤的样式名字和它们的变化。
![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-ng-control-class-changes.png)

相比这对ng-valid | ng-invalid对于我们而言更感兴趣。当数据变为无效并且想标记必填项时我们想发送一个强有力的视觉信号。

在输入框的左侧用一个颜色条可以同时实现两种功能。

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-validity-required-indicator.png)

通过为项目添加一个和index.html平级的新文件styles.css并添加两个样式可以实现这个效果。
styles.css

```Css
.ng-valid[required]{
 
    border-left: 5px solid #422A948;/*绿色*/
}
.ng-invalid{
    border-left:5p solid #a94442;/*红色*/
}
```

这些是为两个angular有效性和HTML5 “必填”属性定制的类选择器。
更新index.html的<head>标签来引入样式文件。
index.html(节选)

```Html
<link rel=”stylesheet” href=”styles.css”>
```

### 显示、隐藏错误信息

我们还能把表单做的更好些。

“Name”输入框是必填的。清空后左边条会变红。这就说明有错误但是我们不知道发生了什么错误或者该做些什么。我们能够借助ng-invalid类来显示一个有用的信息。

当用户删除姓名时会看起来像这样：

![](https://raw.githubusercontent.com/gf-rd/blog/master/assets/angular2-developer-guides/5-name-required-error.png)

实现这种效果需要扩展<input>标签如下：

1. 一个模板局部变量
2. 必填提示信息要在我们仅仅将在控制器变为无效时展示的<div>附近。

为name输入框做这些：
app/hero-form.component.html(节选)

```Html
<input type=”text” class=”form-control” required [(ngModel)]=”model.name” ngControl=”name” #name=”ngForm”>
<div [hidden]=”name.valid || name.pristine” class=”alert alert-danger”>Name is required</div> 
```

添加ngControl指令时，将它绑定到这个模型的名字属性上。

用值”ngForm”(#name=”ngForm”)为模板局部变量(name)设置初始值。Angular能够识别这种语法然后重新设置这个name的模板局部变量来替代这个ngControl指令。换句话说，这个局部变量name会控制变成这个输入框的ngControl对象。

通过绑定<div>元素信息的hidden属性到ngControl对象的valid属性我们现在可以控制这个”name”错误信息的可见性。当控制器是有效时这个信息是隐藏的；当控制器变得无效时这个信息就会显示。

> NgForm指令
我们仅仅使用NgForm指令来设置一个模板局部变量。为什么它就会工作？我们又没有特别的添加NgForm指令。
Angular暗中将他添加到<form>元素的周围。
NgForm指令通过附加功能补充form元素。它搜集controls(通过ngControl指令定义的元素)和监视它们的属性包括有效性检测。它也有它自己的valid属性，仅当每一个它包含的控制器有效时这个valid属性才会为true。

Hero Alter Ego是可选的，我们可以忽略它。

Hero Power复选框是必选项。如果需要我们也能够添加同样的错误信息给select，但这不是必须的，因为选择框已经限制功能为有效的值了。

## 用ngSubmit提交表单

用户填完表单应该能够提交。在表单底部的提交按钮本身不能做任何事情但是却能够监听表单的提交这是因为它的类型(type=”submit”)。

表单提交此刻是没用的。为了让它有用，我们将使用angular指令—NgSubmit更新<form>标签，并用一个事件绑定将它绑定到HeroFormComponent.submit()方法上。

```Html
<form (ngSubmit)=”onSubmit()” #heroForm=”ngForm”>
```

我们在最后添加了一些额外的东西！我们定义了一个模板局部变量—#heroForm，并用”ngForm”来初始化它的值。

这个heroForm变量现在用来操作我们刚刚讨论的NgForm指令，这一次heroForm保留了一个把表单作为整体的参考的形式。

稍后在模板中我们会为按钮绑定disabled属性以确保所有的有效性检查都通过了heroForm。下面是一点代码：

```Html
<button type=”submit” class=”btn btn-default” [disabled]=”!heroForm.form.valid”>Submit</button>
```

再次运行应用。表单会是有效状态，按钮会是激活的。

现在删除我们之前强行给“name 必填项”的错误信息添加的Name。现在提交按钮也变为禁用了。

印象不深刻？思考一下。我们在不借用angular的情况下必须做些什么来控制表单有效性按钮的激活/禁用状态？

对于我们而言，会如此简单：

1. 定义一个模板局部变量（增强）的表单元素。
2. 为按钮大约要写参考那个变量50行的代码。

## 切换表单区域（选学）

提交表单不是可怕的戏剧性时刻。

> 这是一个令人惊讶的示例。老实说，把它搞得有声有色的不会教给我们任何关于表单的新知识。但是这是一个去练习我们新掌握的一些绑定技巧的机会。如果你不感兴趣，可以继续下面的总结。

让我们做一些更惊人的效果。隐藏数据输入部分并展示一些其他的。

首先将表单用一个<div>包裹，并用hidden属性绑定它的HeroFormComponent.submitted属性。

app/hero-form.commonent.html(节选)

```Html
<div [hidden]=”submitted”>
    <h1>Hero Form</h1>
    <form (ngSubmit)=”onSubmit()” #heroForm=”ngForm”>
        <!- … all of the form … ->
    </form>
</div>
```

开始时表单是可见的因为直到我们提交表单前submitted属性都是false，就像这段HeroFormComponent中的代码片段：

submitted = false;onSubmit(){this.submitted = true;}

当我们点击提交按钮时，submitted会变为true并且表单会按照预期那样消失。

当表单提交后我们需要显示一些其他的东西。添加下面的HTML块到我们刚刚写的<div>包裹块的下面：

app/hero-form.commonent.html(节选)

```Html
<div [hidden]=”!submitted”>
    <h2>You submitted the following:</h2>
    <div class=”row”>
        <div class=”col-xs-3”>Name</div>
        <div class=”col-xs-9 pull-left”>{{model.name}}</div>
    </div>
    <div class=”row”>
        <div class=”col-xs-3”>Alter Ego</div>
        <div class=”col-xs-9 pull-left”>{{model.alterEgo}}</div>
    </div>
    <div class=”row”>
        <div class=”col-xs-3”>Power</div>
        <div class=”col-xs-9 pull-left”>{{model.power}}</div>
    </div>
    <br>
    <button class=”btn btn-default” (click)=”submitted=false”>Edit</button>
</div>
```

我们hero信息又出现了，但仅仅是插值的绑定信息。这段HTML仅仅在组件是submitted状态时出现。

我们添加了一个绑定清空submitted表达式Edit按钮。

当我们点击它时，这一块会消失然后可输入的表单会重现。

这是目前我们能做到的最好了。

## 总结

这章讨论了angular2表单提供数据修正、有效性检以及下面这些优势：

1. angular表单模板
2. 带有Component修饰的表单组件类
3. 控制表单提交的ngSubmit指令
4. 类似#heroForm,#name,#alter-ego,#power的模板局部变量
5. 双向数据绑定的ngModel指令
6. 有效性检测和监视表单元素改变的ngControl
7. 表单控件局部变量的valid属性是否有效的检查和显示/隐藏错误信息
8. 通过绑定NgForm来控制表单提交按钮的激活状态
9. 自定义CSS类来为用户提供关于错误信息的可视效果

项目文件夹最后看起来像这样：

├──node_modules

├── app

|          ├── app.component.ts

|          ├── boot.ts

|          ├── hero.ts

|          ├── hero-form.component.html

|          └── hero-form.component.ts

├── index.html

├── styles.css

├── tsconfig.json

└── package.json

 这是最终版本的代码：
hero-form.component.ts

```Javascript
import {Component} from “angular2/core”;
import {NgForm} from “angular2/common”;
import { Hero } from “./hero”;
 
@Component({
    selector: “hero-form”,
    templateUrl: “app/hero-form.component.html”
})
export class HeroFormComponent {
    powers = [“Really Smart”, “Super Flexible”,“Super Hot”, “Weather Changer”];
    model = new Hero(18, “Dr IQ”, this.powers[0], “Chuck Overstreet”);
    submitted = false;
    onSubmit() { this.submitted = true; }
}
```

hero-form.component.html

```Html
<div class=”container”>
    <div [hidden]=”submitted”>
        <h1>Hero Form&</h1>
        <form (ngSubmit)=”onSubmit()” #heroForm=”ngForm”>
            <div class=”form-group”>
                <label for=”name”>Name</label>
                <input type=”text” class=”form-control” required [(ngModel)]=”model.name” ngControl=”name” #name=”ngForm”>
                <div [hidden]=”name.valid” class=”alert alert-danger”> Name is required</div>
            </div>
            <div class=”form-group”>
                <label for=”alterEgo”>Alter Ego</label>
                <input type=”text” class=”form-control” [(ngModel)]=”model.alterEgo” ngControl=”alterEgo” >
            </div>
            <div class=”form-group”>
                <label for=”power”>Hello Power</label>
                <select class=”form-control” required [(ngModel)]=”model.power” ngControl=”power” #power=”ngForm”>
                    <option *ngFor=”#p of powers” [value]=”p”>{{p}}</option>
                </select>
                <div [hidden]=”power.valid” class=”alert alert-danger”> Power is required</div>
            </div>
            <button type=”submit” class=”btn btn-default” [disabled]=”!heroForm.form.valid”>Submit</button>
        </form>
    </div>
    <div [hidden]=”!submitted”>
        <h2>You submitted the following:</h2>
        <div class=”row”>
            <div class=”col-xs-3”>Name</div>
            <div class=”col-xs-9 pull-left”>{{ model.name }}</div>
        </div>
        <div class=”row”>
            <div class=”col-xs-3”>Alter Ego</div>
            <div class=”col-xs-9 pull-left”>{{ model.alterEgo }}</div>
        </div>
        <div class=”row”>
            <div class=”col-xs-3”>Power</div>
            <div class=”col-xs-9 pull-left”>{{ model.power }}</div>
        </div>
        <br>
        <button class=”btn btn-default” (click)=”submitted=false”>Edit</button>
    </div>
</div>
```

hero.ts

```Javascript
export class Hero {
    constructor(
        public id: number,
        public name: string,
        public power: string,
        public alterEgo?: string
    ){}
}
```

app.component.ts

```Javascript
import {Component} from ‘angular2/core’;
import {HeroFormComponent} from ‘./hero-form.component’;
 
@Component({
    selector: ‘my-app’,
    template: ‘<hero-form></hero-form>’,
    directives: [HeroFormComponent]
})
 
export class AppComponent { }
```

boot.ts

```Javascript
import {bootstrap} from  ‘angular2/platform/browser’;
import {AppComponent} from ‘./app.component’;
 
bootstrap(AppComponent);
```

index.html

```Html
<html>
    <head>
    <title>Hero Form</title>
    <link rel=”stylesheet” href=”node_modules/bootstrap/dist/css/bootstrap.min.css”>
    <link rel=”stylesheet” href=”styles.css”>
    <script src=”node_modules/angular2/bundles/angular2-polyfills.js”></script>
    <script src=”node_modules/systemjs/dist/system.src.js”></script>
    <script src=”node_modules/rxjs/bundles/Rx.js”></script>
    <script src=”node_modules/angular2/bundles/angular2.dev.js”></script>
    <script>
        System.config({
            packages: { 
                app: {
                    format: “register”,
                    defaultExtension:“js”
                }
            }
        });
        System.import(“app/boot”).then(null,console.error.bind(console));
    </script>
</head>
<body>
    <my-app>Loading...</my-app>
</body>
</html>
```

styles.css

```Css
.ng-valid[required] {
    border-left:5px solid #42A948; /* green */
}
.ng-invalid {
    border-left:5px solid #a94442; /* red */
}
```

>### 下一章
> [6. 依赖注入](https://github.com/gf-rd/blog/issues/12)

**Comment by coyuanye** [comment]
示例代码以TypeScript为例

表单可以是紧密结合的，有效的，令人信服的数据录入。一个angular表单可以实现用户控制，监视变化，验证输入和错误信息处理，数据绑定等功能。

我们经常使用表单来实现登录，寻找帮助，下订单，订机票，安排会议和执行数不胜数的其他数据任务。表单是商务应用的支柱。

任何经验丰富的web开发人员能够直接使用正确的标签完成一个html表单。创建一个集成可以暗中高效并且有效引导用户数据录入的表单具有挑战性。

这章就主要是讨论这方面的技巧。

这章我们也将探讨angular表单关于双向绑定，实时监视，有效性检测和出错处理的支持。

接下来我们将创建一个简单的表单，每次一个步骤。并按如下步骤来学习：
* 如何用一个组件和模板来创建一个angular表单
* ngModel双向数据绑定的读写语法和在input中的值
* ngControl指令监视表单的变化状态和数据有效性检测
* ngControl添加给表单的特殊的CSS类，并用该如何使用这些类来提供明显的可视效果
* 如何向用户展示错误信息和激活/禁用表单
* 如何通过控制模板局部变量来展示信息

## 模板驱动表单

大多数人会通过使用带有表单特殊指令和这章描述的技术的angular模板语法书写模板来创建表单。

> 这不是唯一的方式去创建一个表单但这将是我们这一章的方式

使用angular的模板我们几乎可以创建任何一个我们需要的表单—登录表单、联系表单…几乎所有的商务表单。我们可以创造性的使用，为他们绑定数据，特殊的校验规则和展示错误信息，条件性的激活/开启控制，触发内置的可视效果，甚至更多功能。

由于angular处理了很多重复的任务，并有示例，这样我们用起来将会相当容易，否则我们将会处理这些苦恼的事情

我们将会探讨并且学习如何创建一个下面这种模板驱动型表单：
![](https://github.com/gf-rd/blog/blob/master/assets/angular2-developer-guides/5-hero-form-1.png)

**Comment by coyuanye** [comment]
angular2-5.forms

**Comment by coyuanye** [comment]
angular2-5.forms

**Comment by coyuanye** [comment]
angular2-5.forms

**Comment by coyuanye** [comment]
angular2-5.forms

**Comment by coyuanye** [comment]
修改图片链接

**Comment by flyher** [comment]
@coyuanye 
正好看到这儿，发现这里需要修改一下：
### 创建表单组件 
栏目中
```js
import {Compontent} from ‘angular2/core’;
import {NgForm} from ‘angular2/common’;
import {Hero} from ‘./hero’;
@Component ({
    selector: ‘hero-form’, 
    templatrUrl: ‘app/hero-form.compontent.html //templatrUrl需要改为templateUrl
})
export class HeroFormCompent {//HeroFormCompent需要改为HeroFormComponent，因为你在下面引用的是这个名称HeroFormComponent
    powers = [‘ReallySmart’,’Super Flexible’,’Super Hot’,’Weather Changer’];
    model=new Hero(18,’DrIQ’,this.powers[0],’Chuck Overstreet’);
    submitted = false;
    onSubmitt(){this.submitted= true;}
    //TODO:Remove this when we’re done get diagnostic(){return JSON.stringify(this.model);
}}
```

**Comment by zhailei31665431** [comment]
中间往styles.css里面写的样式错误了，请修正。

**Comment by JTangming** [comment]
状态	                     如果Class为True	如果Class为False
控制器被访问	          ng-touched	         ng-untouched
控制器被访问	          ng-untouched	 ng-untouched
控制器的值是有效地  ng-untouched	 ng-invalid
----------
这个表格里的内容有误，请参考官网原文.

**Comment by YeaseonZhang** [comment]
State	                  Class if true	    Class if false
控制器被访问	          ng-touched	    ng-untouched
控制器的值已改变      ng-dirty	            ng-pristine
控制器的值有效         ng-valid	            ng-invalid
@coyuanye 请修改与官网一致

**Comment by YeaseonZhang** [comment]
`.ng-valid[required] {
  border-left: 5px solid #42A948; /* green */
}

.ng-invalid {
  border-left: 5px solid #a94442; /* red */
}`

> 表单验证CSS部分代码有误。

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
