### ISSUE TITLE
【Angular2开发指南】13.分级注入

### ISSUE THREAD

**Issue by michaeltyhuang** [gf-rd/blog#25]
# 分级注入

>Angular的分级依赖注入系统支持与组件树并行嵌套注入方式。

>基本的Angular依赖注入原则我们可以在《第六章：依赖注入》里面查找。

>Angular 有一套分级依赖注入系统。其实它是一颗依赖注入树。

>我们可以在组件树里面的任何层级中重新配置注入器，并且得到很有趣且有用的结果。

# 注入树
>在《第六章：依赖注入》里面我们学到了如何配置依赖注入，还有如何在需要的时候获取依赖。

>然而，第六章我们描述的过于简单了。 事实上，Angular不止一个注入器，而是有很多个。

>一个Angular 应用其实是一颗组件树。每一个组件都拥有自己的注入器。也就是说组件和注入器是一一对应的平衡关系。

>注：

>每一个组件都有一个注入器（注入器其实也可以share），所以会有很多不同的注入器实例来控制不同层级的组件树。

>每个组件拥有自己的注入器，你这样理解就没错了。

>让我们看看下面的例子，这一颗组件树一共有三种组件——  HerosApp、HerosListComponent、HerosCardComponent.

>HerosApp拥有一个HerosListComponent实例，HerosListComponent拥有三个HerosCardComponent实例。

![image](https://cloud.githubusercontent.com/assets/5189056/12163808/7c5d675e-b54b-11e5-8d6a-f24ed0f0b448.png)

>上面说到其实每一个组件都拥有自己的注入器实例。

>举个例子说明，如最底层的HeroesCardComponent组件请求一个依赖，它就会问自己注入器实例索取这个依赖。

>注入器实例会遍历已经注册到自己身上的provider。如果注入器实例找不到该provider，就会询问自己的父亲注入器实例（这个例子父亲注入器就是HerosListComponent组件的注入器实例）。

>如果连父亲那都找不到的话，就再往上找爷爷的，最后如果到了Angular根节点都找不到的话，就抛出异常。

>注意:

>这里有种特殊情况，一个中间组件可以宣称自己就是一个“host”组件。这样可以让注入器实例停止往父亲注入器索取依赖。这种情况我们以后再谈。

>再举一个例子。

>我们举一个Car（车）做例子。假如A组件的注入器注册了Car（车）依赖、Engine（发动机）依赖、Tires（轮胎）依赖。

>组件B是A的儿子组件，它的注入器注册了Car（车）依赖、Engine（发动机）依赖。

>组件C是B的儿子，A的孙子，它的注入器注册了Car（车）依赖。

>背后的原理是每一个层级的组件会初始化自己的注入器实例，创建注入器实例的时候，输入参数是一个或多个provider（车、发动机、轮胎）。这些参数既注册在注入器（injector）上，也定义在组件（component）中。

>当我们在处理组件C的时候，会处理注册在注入器C上的Car（车）依赖实例。

>Car依赖的创建需要组件B上的Engine（发动机），也需要组件上得Tires（轮胎）。

>直观流程为： 组件C ->注入器C ->注册了 provider Car 依赖 ，为了获得这个依赖实例  - > 去父亲组件B上寻找 provider Engine （有了发动机才能组装车子的嘛） -> 去爷爷组件A上寻找 provider Tires （有了轮胎才能组装车子） -> 得到了Tires，Engine，组装成Car实例供组件C用（这一过程用promise来实现）

![image](https://cloud.githubusercontent.com/assets/5189056/12163833/c0bf054c-b54b-11e5-93e7-36d75d11748d.png)

# 组件注入器

>在上一个小节，我们讨论了注入器（injector）还有它们是如何组织成树结构的。了解了注入器（injector）怎么向父亲，爷爷一直到根节点来询问获取自己的依赖。

>但是问题来了，我们怎么知道什么时候需要把依赖注册到自身注入器，什么时候把依赖注入到父亲的注入器呢？

>下面来看看一个例子，你要建立一个组件（component）去展示一组超级英雄，每一个英雄的名字、超能力要在一个卡片（card）上。

>每一个卡片需要一个修改（edit）按钮，让用户修改对应英雄的名字和超能力。

>其中一个很重要的需求是： 可以同时修改或者取消修改每一个英雄，也就是说每一个超级英雄都可以独立修改，互补干扰。

>好，话不多说，来看看代码：

app/heroes-list.component.ts
```js
import {Component} from 'angular2/core';
import {EditItem} from './edit-item';
import {HeroesService} from './heroes.service';
import {HeroCardComponent} from './hero-card.component';
import {HeroEditorComponent} from './hero-editor.component';
import {Hero} from './hero';
@Component({
selector: 'heroes-list',
 template: `
    <div>
     <ul>
        <li *ngFor="#editItem of heroes">
          <hero-card
           [hidden]="editItem.editing"
           [hero]="editItem.item">
          </hero-card>
          <button
            [hidden]="editItem.editing"
            (click)="editItem.editing = true">
            edit
          </button>
         <hero-editor
            (saved)="onSaved(editItem, $event)"
            (canceled)="onCanceled(editItem)"
            [hidden]="!editItem.editing"
            [hero]="editItem.item">
         </hero-editor>
        </li>
      </ul>
    </div>`,

  directives: [HeroCardComponent, HeroEditorComponent]
})
export class HeroesListComponent {
   heroes: Array<EditItem<Hero>>;
   constructor(heroesService: HeroesService) {
     this.heroes = heroesService.getHeroes()
     .map(item => new EditItem(item));
   }

  onSaved (editItem: EditItem<Hero>, updatedHero: Hero) {
    editItem.item = updatedHero;
    editItem.editing = false;
  }

   onCanceled (editItem: EditItem<Hero>) {
    editItem.editing = false;
   }
}

```

>可以注意到上述代码引入了 HeroService 这个service，因为以前的章节已经定义过了，这里不再重复。下面看看我们怎么对英雄（hero）建立class。

app/hero.ts

```js
export class Hero { name: string; power: string; }
```

>HeroesListComponent 在模板里面定义了HeroCardComponent 和 HeroEditorComponent，然后list里面的每一个元素都绑定了一个由HeroService提供的英雄。

>以上说法不完全正确。

>其实list里面的每个元素绑定到 EditItem<Hero> 上面了。这个数据类型可以包裹任何类型。

app/edit-item.ts

```js
export class EditItem<T> { 
 editing: boolean 
 constructor (public item: T) {} }
```

>下面是HeroCardComponent 的实现。

app/hero_card.component.ts

```js
import {Component, Input} from 'angular2/core';
import {Hero} from './hero';

 @Component({
    selector: 'hero-card',
    template: `
     <div>
      <span>Name:</span>
      <span>{{hero.name}}</span>
     </div>`
  })

  export class HeroCardComponent {
     @Input() hero: Hero;
   }
```

>HeroCardComponent 组件只是定义一个模板来展示这个超级英雄，没啥的。

>下面看看最有趣的部分—— HeroEditorComponent的实现吧 。

app/hero-editor.component.ts

```js
import {Component, Input, Output, EventEmitter} from 'angular2/core';
import {RestoreService} from './restore.service';
import {Hero} from './hero';

 @Component({
   selector: 'hero-editor',
   providers: [RestoreService],
   template: `
     <div>
      <span>Name:</span>
      <input [(ngModel)]="hero.name"/>
     <div>
      <button (click)="onSaved()">save</button>
      <button (click)="onCanceled()">cancel</button>
     </div>
    </div>`
 })

export class HeroEditorComponent {
  @Output() canceled = new EventEmitter();
   @Output() saved = new EventEmitter();

   constructor(private restoreService: RestoreService<Hero>) {}
     @Input()
     set hero (hero: Hero) {
      this.restoreService.setItem(hero);
     }

     get hero () {
      return this.restoreService.getItem();
     }

    onSaved () {
      this.saved.next(this.restoreService.getItem());
     }

    onCanceled () {
      this.hero = this.restoreService.restoreItem();
      this.canceled.next(this.hero);
     }
 }
```
>这里就是有趣的部分了。 HeroEditorComponent定义了“保存”和“取消”按钮用以改变英雄名字和能力。

>我们的需求是每个英雄可以独立修改，互补影响。这意味着我们要保存两份值，一份是修改前的值，一份是新值。

>回想一下，这不就是一个很好的用例来说明兄弟组件（component）可以拥有自己的service实例。

>下面 RestoreService 粉墨登场。

app/restore.service.ts

```js
export class RestoreService<T> {
    originalItem: T;
    currentItem: T;

    setItem (item: T) {
      this.originalItem = item;
      this.currentItem = this.clone(item);
     }

    getItem () :T {
      return this.currentItem;
     }

    restoreItem () :T {
      this.currentItem = this.originalItem;
      return this.getItem();
     }

    clone (item: T) :T {
      // super poor clone implementation
      return JSON.parse(JSON.stringify(item));
     }
 }
```
>这个小服务（service）的用途就是可以设置（set）值，然后获取（get）设置过的值等。

>HeroEditComponent 拦截设置（set）和获取（get）方法，然后把真正的工作代理给RestoreSerice这个服务。

>到这里，你可能会饶头自问：啥？这跟组件注入没有一毛钱关系啊？

>别急，认真看看我们定义的HeroEditComponent。里面有如下定义：

```js
 providers: [RestoreService],
```
>这里把RestoreService 添加到 HeroEditComponent组件的注入器（injector）中。

>我们能不能直接在 bootstrap方法里面实现呢？

>答案是不能！！！！！

```js
bootstrap(HeroesListComponent, [HeroesService, RestoreService])
```
>虽然程序上我们可以这样写，但是我们组件的实现需求不允许我们这么做。 记得我们需要每一个注入器需要一个独立的RestoreService实例，也就是说，RestoreService实例对于 每一个HeroEditComponent来说是单例的。

```js
 providers: [RestoreService], 
```
>这种写法就是让Angular知道 每一个HeroEditComponent都需要一个新的RestoreService实例。

>是不是意味着 服务（service）在angular 2 中不再是单例模式呢？ 答案 既“是”也“不是”。对于一个注入器实例来说，服务是单例的。但是 我们知道Angular 2 可以有多个 注入器（injector）作用于不能层级的组件（component）上。每一个注入器都可以拥有自己的 服务（service）实例。

>如果我们在根节点（root component）定义 一个RestoreSerivce的话，我们就仅仅只有一个RestoreService实例，并且在整个app中共享这个实例。

>### 下一章
>[14. 从1.x升级到2.0](https://github.com/gf-rd/blog/issues/15)

**Comment by CK110** [comment]
挑个小毛病吧，hero_card.component.ts ，官网上是hero-card.component.ts

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
