### ISSUE TITLE
【Angular2开发指南】15.词汇表

### ISSUE THREAD

**Issue by zhongyanms** [gf-rd/blog#26]
<body>
<p>在angular2词汇中一些比较重要的定义。</p>

<h2 id="toc_0">Angular2 词汇表</h2>

<p>angular它自己的词汇。大多angular词汇是日常英语单词，但在angular系统内有其特定含义。</p>

<p>我们在这里搜集了一些比较重要的和一些不太常见的或者特别的词汇定义。</p>

<h2 id="toc_1">Annotation 注释</h2>

<p>在实际操作中，注释作为一个<a href="#toc_9">装饰</a>的代名词。</p>

<h2 id="toc_2">Attribute Directive 属性指令</h2>

<p>angular的<a href="#toc_11">指令</a>之一，可以监听和修改其他html元素、属性、性能和组件。他们通常与html属性有关，因此得名。</p>

<p>添加和移除CSS类名的<strong>ngclass</strong>就是属性的指令的一个很好的例子。</p>

<h2 id="toc_3" name="toc_3">Barrel</h2>

<p>Barrel是由单一却包含完整逻辑组成的angular库模块，如angular的<strong>Component</strong>和指令<strong>Directive</strong>。</p>

<p>常见的angular barrel包括<strong>angular2/core， angular2/common， angular2/platform/browser ，angular2/http</strong>和<strong>angular2/router</strong>。</p>

<p>Barrel可以像<a href="#toc_6">bundles</a>一样在我们的index.html的script标签内进行Barrel的打包和绑定 。</p>

<p>如脚本<strong>angular2.dev.js</strong>就是一个包。</p>

<p>了解更多“<a href="https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md">Modules, barrels and bundles</a>”。</p>

<h2 id="toc_4">Binding 绑定</h2>

<p>大多数时候指数据绑定（<a href="#toc_8">data binding</a>），或一个HTML属性对象绑定到一个数据属性对象的行为。</p>

<p>有时候指在一个 &quot;token&quot; 值或”key&quot;值中<a href="#toc_10">依赖注入</a>，又或者是 dependency <a href="#toc_19">provider</a>。
更多的用法参见上下文。</p>

<h2 id="toc_5" name="toc_5">Bootstrap 引导程序</h2>

<p>我们可以用通过“bootstrapping”启动该应用的引导程序来启动一个angular应用。 该引导程序可识别应用中的“根（根作用域）” 组件和在<a href="#toc_10">依赖注入系统</a>中可选的指定service <a href="#toc_19">providers</a>。</p>

<p>每个应用都有它自己的顶层根作用域，bootstrap也可以在同一个<strong>index.html</strong>引导的多个不同的应用程序。</p>

<h2 id="toc_6" name="toc_6">Bundle 束</h2>

<p>Angular JavaScript库捆绑于npm安装包中 ，如<a href="https://www.npmjs.com/package/angular2">angular2</a>。</p>

<p>又或者更为熟悉的脚本angular2.dev.js和http.js router.js Rx.js等。</p>

<p>一个bundle包含一个或多个的<a href="#toc_3">barrels</a>，而每个barrel包含逻辑相关的集合<a href="#toc_17">模块</a>。</p>

<p>常见的barrel包括angular2/core angular2/common angular2/platform/browser angular2/http angular2/router 。</p>

<p>了解更多“<a href="https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md">Modules, barrels and bundles</a>”。</p>

<h2 id="toc_7" name="toc_7">Component 组件</h2>

<p>angular负责显示数据到<a href="#toc_26">界面</a>中和处理界面展示和用户交互的逻辑。</p>

<p>组件是在angular系统中最重要的部分。组件往往包含一个angular<a href="https://github.com/gf-rd/blog/issues/22">指令</a>与相对应的<a href="#toc_28">模板</a>。</p>

<p>开发人员运用<strong>@Component</strong>这样的<a href="https://angular.io/docs/ts/latest/guide/decorator">装饰器</a>到组件类，Angular首先会创建一个组件模块，并把它作为一个界面模版呈现，从而连接组件元数据到对应的class。</p>

<p>熟悉“MVC”和“MVVM”模式的人更能认识到&quot;Controller&quot; or &quot;View Model&quot;在angular中的重要性。</p>

<h2 id="toc_8" name="toc_8">Data Binding 数据绑定</h2>

<p>应用程序呈现数据值给用户，和响应用户（clicks, touches, keystrokes）等动作事件。</p>

<p>但现在我们可以通过纯手动把应用程序的数据值传进HTML，添加事件监听，拉取改变值，并更新应用程序的数据值......</p>

<p>同时，我们可以声明一个HTML小模块与应用程序数据源之间的关系（就可以实现model和view的双向绑定）......并让数据对应绑定的框架处理更多逻辑执行。</p>

<p>Data Binding只是其中一种方法，angular拥有丰富的数据绑定模式和支持声明的语法。</p>

<p>这些包括：</p>

<blockquote>
<p><a href="https://github.com/gf-rd/blog/issues/18">插值</a>
<a href="https://github.com/gf-rd/blog/issues/18">对象属性绑定</a>
<a href="https://github.com/gf-rd/blog/issues/18">事件绑定</a>
<a href="https://github.com/gf-rd/blog/issues/18">标签属性绑定</a>
<a href="https://github.com/gf-rd/blog/issues/18">Class类绑定</a>
<a href="https://github.com/gf-rd/blog/issues/18">Style样式绑定</a>
<a href="https://github.com/gf-rd/blog/issues/18">ngModel双向数据绑定</a>
</p>
</blockquote>
<p>了解更多关于数据绑定可参看<a href="https://github.com/gf-rd/blog/issues/18">Template Syntax</a>章节。</p>

<h2 id="toc_9" name="toc_9">Decorator | Decoration 装饰器</h2>

<p>Decoration 是一个函数，用来增加元数据到类，它包括（属性，方法）和函数参数。</p>

<p>装饰是JavaScript的一个语言<a href="https://github.com/wycats/javascript-decorators">特性</a>，出现在TypeScript中和提出在ES2016（AKA ES7）。</p>

<p>我们会把装饰器运用在需要装饰的地方的上方或左侧。</p>

<p>Angular有它自己的一套decorators，这种decorators可以帮助angular与我们的应用程序的某部分进行互操作。下面是一个示例 @Component 装饰，用来识别某一个类为angular的一个组件和应用于该组件属性的 @Input 装饰。 消隐对象参数的@Component装饰将包含相关的组件元数据</p>

<pre><code class="language-none">@Component({...}) export class   AppComponent { constructor(@Inject(&#39;SpecialFoo&#39;) public foo:Foo) {} @Input() name:string; }</code></pre>
 
<p>一个decorator的范围局限于它装饰的范围。没有装饰器会“泄漏”出现在它下面的文件中其他类。</p>

<pre><code class="language-none">装饰器的内容必须用()包住。 装饰是一个被请求时必须调用的函数。</code></pre>

<h2 id="toc_10" name="toc_10">Dependency Injection 依赖注入</h2>

<p>依赖注入是一个很重要的设计模式和机制，当这个应用程序的某一部分需要另一部分的时候，依赖注入就是用来创建或者传递这一部分。</p>

<p>Angular开发者更喜欢通过定义许多简单的组件，每一组件是一个完整的逻辑，然后把它们连接在一起的运行。</p>

<p>这些组件通常依赖于其他组件。 一个Angular<a href="#toc_7">组件</a>的可能依赖一个获取接口数据或执行操作计算的组件。 当“A”依赖“B”，我们说“A”依赖“B”而“B”是“A”的依赖注入。</p>

<p>我们可以让一个“<a href="https://github.com/gf-rd/blog/issues/12">依赖注入系统</a>”，创建一个“A”为我们处理所有的依赖注入关系。 如果“A”需要“B”而“B”需要“C”，这个“依赖注入系统”解决了所有相关依赖注入的连接，并且返回完整的“A”。</p>

<p>Angular提供并依靠自己的先进的依赖注入系统和运行应用程序，当需要时用&quot;injecting&quot;把应用程序某一部分并入另一部分中。</p>

<p>这个机制的核心是<a href="#toc_14">Injector</a>，他能返回请求的依赖值。injector.get(token)返回给定的token关联的值。</p>

<p>token是一个Angular 类型 ( OpaqueToken )。我们很少直接处理taken，大多时候我们将 class name ( Foo ) or a string (&quot;foo&quot;) 和 Angular 转换为一个token。 当我们写injector.get(Foo)的时候，注入返回class Foo 的token相关的值，那通常是一个Foo本身。</p>

<p>当需要一个展示组件，Angular内部会发出很多类似的请求在它运行期间。</p>

<p>该Injector包含一个相关token值的内部地图。 如果Injector不能找到一个给定的token值，它就会用一个Provider创建一个新的token值。</p>

<p>一个<a href="#toc_19">Provider</a>是给特定token创建新的相关依赖值的主要方式。</p>

<p>injector 只能创建一个值给一个给定的token，如果一个token在其内部拥有一个指定的Provider。 该指定将是很关键一节。</p>

<p>Angular为每一个 injector指定了对应Provider。我们可以指定自己的Provider。在<a href="#toc_5">引导应用程序</a>前指定Provider是最好的，但是在其他时候指定Provider也是可以的。</p>

<p>了解更多的<a href="https://github.com/gf-rd/blog/issues/12">Dependency Injection</a>一章。</p>

<h2 id="toc_11" name="toc_11">Directive 指令</h2>

<p>Angular类负责创建，重绘，并在浏览器的DOM层与HTML元素进行交互。Directive是Angular的最基本的特性之一。</p>

<p>Directive总是与一个HTML元素或属性相关。我们通常把这样的元素或属性看作Directive本身。当Angular度发现一个Directive在HTML模板，它就会创建相匹配的Directive类，并给出了该部分浏览器的DOM的控制。</p>

<p>开发人员可以自定义创造的HTML标记(e.g., <my-directive>) 与他们的自定义指令相关联。当他们编写本地的HTML时候他们添加这个自定义标记到HTML模板。用这种方式，Directive成为HTML本身的扩展。</p>

<p>Directive分为三类：</p>

<p><a href="#toc_7">组件</a>，结合应用逻辑与HTML模板来呈现应用程序的组件[观点]。 组件通常表示为HTML元素。它是一个Angular应用程序的基建部分，开发人员可以延伸开展到很多东西。</p>

<p><a href="https://github.com/gf-rd/blog/issues/22">属性指令</a>，它可以监听和修改其他HTML元素，属性，对象和组件。 他们通常表示为HTML属性，因此而得名。</p>

<p><a href="https://github.com/gf-rd/blog/issues/14">结构指令</a>，负责调整或重绘HTML布局，通常通过添加，删除或操纵元素及其子元素。</p>

<h2 id="toc_12" name="toc_12">ECMAScript</h2>

<p>The <a href="https://en.wikipedia.org/wiki/ECMAScript">official JavaScript language specification</a>（官方的JavaScript语言规范 ）</p>

<p>JavaScript的最新版本是<a href="http://www.ecma-international.org/ecma-262/6.0/"> ECMAScript 2015</a>（又名“ES2015”或“ES6”），许多Angular2开发人员开发他们的程序使用这个版本的JavaScript （ES6）或者它的兼容延伸语言例如<a href="#toc_25">TypeScript</a>。目前大多浏览器只支持先前“的ECMAScript 5”（又名ES5）标准。用ES2015或它的延伸语言写的应用程序必须先“<a href="https://angular.io/docs/ts/latest/guide/transpile">transpiled</a>”成ES5版JavaScript。</p>

<p>Angular2开发者可能会选择直接使用 ES5。</p>

<p>ECMAScript 2015</p>

<p>JavaScript的最新的版本<a href="http://www.ecma-international.org/ecma-262/6.0/">ECMAScript 2015</a>(AKA &quot;ES2015&quot; or &quot;ES6&quot;)</p>

<p>ES2015</p>

<p>Short hand for &quot;<a href="http://www.ecma-international.org/ecma-262/6.0/">ECMAScript 2015</a>&quot;.</p>

<p>ES6</p>

<p>Short hand for &quot;<a href="http://www.ecma-international.org/ecma-262/6.0/">ECMAScript 2015</a>&quot;.</p>

<p>ES5</p>

<p>Short hand for “ECMAScript 5”，JavaScript的版本通过最现代的浏览器中运行。 详见<a href="https://angular.io/docs/ts/latest/guide/glossary.html#ecmascript=2015">ECMAScript</a>。</p>

<h2 id="toc_13">Injector 注射器</h2>

<p>如果一个对象存在Angular<a href="#toc_10">依赖注入系统</a>中 ，也可以找到它对应的“依赖”在缓存中或用指定的 <a href="#toc_19">provider</a>创建一个这样的对象。</p>

<h2 id="toc_14"  name="toc_14">Input 输入</h2>

<p>一个指令属性可以跟一个模版<a href="https://github.com/gf-rd/blog/issues/18">对象绑定</a>。 数值从数据源传入特定的模板表达式中。</p>

<p>见<a href="https://github.com/gf-rd/blog/issues/18">Template Syntax</a>篇章。</p>

<h2 id="toc_15">Interpolation 插值</h2>

<p>一种绑定在一个模板里双大括号之间呈现为文本形式的属性数据。 在下面的例子中你可以看到该文本可以与相邻的文本串联在一起，在它被分配给一个元素属性之前或者展示在两个元素标签之间。</p>

<pre><code class="language-none">My current hero is {{hero.name}} 我现在的英雄是{{hero.name}}</code></pre>

<p>了解更多关于插值的知识在<a href="https://github.com/gf-rd/blog/issues/18">Template Syntax</a>篇章。</p>

<h2 id="toc_16">Lifecycle Hooks 生命周期钩子</h2>

<p><a href="#toc_11">指令</a>和<a href="#toc_7">组件</a>拥有一定的生命周期，受到Angular约束，因为Angular能创建，更新和删除这些指令或者部件。</p>

<p>开发人员可以使一个或者多个的“生命周期钩子”执行，通过在关键入口切入生命周期。</p>

<p>每个都有一个单独的钩子，这个钩子的前缀名都包含<strong>ng</strong>。 例如，所述<strong>OnInit</strong>钩子名<strong>ngOnInit</strong></p>

<p>Angular调用按以下顺序这些挂钩方法：</p>

<p>ngOnChanges -当一个所谓的输入 / 输出值绑定变化</p>

<p>ngOnInit -第一后ngOnChanges</p>

<p>ngDoCheck -开发者自定义变化检测</p>

<p>ngAfterContentInit -后成分含量初始化</p>

<p>ngAfterContentChecked -的成分含量每次检查后，</p>

<p>ngAfterViewInit -组件的视图（S）初始化后，</p>

<p>ngAfterViewChecked -一个组件的视图的每个检查后（S）</p>

<p>ngOnDestroy -就在该指令被破坏。</p>

<p>了解更多在<a href="https://github.com/gf-rd/blog/issues/13">生命周期钩子</a>的篇章。</p>

<h2 id="toc_17" name="toc_26">Module</h2>

<p>Angular 应用都是模块化的。</p>

<p>通常，我们的应用是由很多模块组成的，包括自己写的和第三方模块。</p>

<p>一个典型的模块就是一组专注某个目标的代码块。</p>

<p>模块 导出 代码块里面的某些内容，典型地就是导出一个类，如果其它模块需要这个类，那么就 导入 这个类。</p>

<p>Angular 模块结构 以及 导入/导出 语法是基于<a href="#toc_12">ES2015</a>标准的。</p>

<p>如果要遵循 ES2015 标准则需要一个模块加载器，用于请求加载模块，以及解析模块间的依赖。Angular 没有配备一个模块加载器，也没有一个特别适合的第三方模块加载器（尽管很多例子都用 SystemJS）。开发者可以挑任何符合标准的模块库。</p>

<p>通常在确定好模块的导出内容后才给模块命名。例如 Angular 的<a href="https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/date_pipe.ts">DatePipe</a>类，属于date<em>pipe功能模块，这个模块定义在 date</em>pipe.ts 文件，</p>

<p>开发者很少直接访问 Angular 的功能模块，通常我们是从公开使用的 模块包 中导入一些功能模块，这种模块包，我们称之为<a href="#toc_3">barrels（模块组)</a>。Barrel就是一组逻辑相关的模块。angular2/core 模块组就是最好的例子。</p>

<p>查看 &quot;<a href="https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md">Modules, barrels and bundles</a>&quot; 了解更多.</p>

<h2 id="toc_18">Pipe</h2>

<p>Angular 的管道就是一个方法，用来把输入值转换为<a href="#toc_26">视图</a>上的输出值。我们使用 @Pipe <a href="#toc_9">装饰器</a> 来关联管道函数，并指定名称。</p>

<p>下面例子使用内置的 currency 管道函数来展现一个本地化的货币数字。</p>

<pre><code class="language-none">&lt;label&gt;Price: &lt;/label&gt;{{product.price | currency}}</code></pre>

<h2 id="toc_19" name="toc_19">Provider</h2>

<p>在依赖注入时，Provider 会创建一个所依赖的实例。它涉到一种代码标记扫描规则－通常也叫“代码食谱”－用来创建一个所依赖的值。</p>

<p>例如，new Provider(Foo, {useClass: Foo}) 创建一个 Provider，该 Provider 把 Foo 关联到一个创建 ｀Foo类｀实例的方法。</p>

<p>有很多方式来创建这种“标记”和“代码谱”。可以查看<a href="#toc_10">依赖注入</a>章节了解更多。</p>

<h2 id="toc_20">Router（路由）</h2>

<p>大多数应用包涵很多界面或者<a href="#toc_26">视图</a>。用户通过点击链接、按钮或其它类似操作来替换视图，从而实现在各种视图界面之间跳转。</p>

<p>Angular 路由器具有一套功能丰富的机制，用于配置和管理视图导航跳转，还包括管理视图的创建和销毁。</p>

<h2 id="toc_21">Routing Component（路由组件）</h2>

<p>一种关联了路由功能的<a href="#toc_7">组件</a></p>

<p>该组件使用 @RouterConfig 装饰器定义视图路由映射，从而关联控制<a href="#toc_20">路由</a>。</p>

<p>该组件的模板会有一个 RouterOutlet 元素，可用来显示路由定义的视图。</p>

<p>路由组件通常有一些 RouterLink 指令生成的锚点标签或者按钮，可以让用户点击然后跳转。</p>

<h2 id="toc_22">Structural Directive（结构指令）</h2>

<p>某个 Directive 种类，通常通过添加、删除、操作元素或其孩子，从而实现一次或者多次改变 HTML 布局。</p>

<p>ngIf &quot;条件元素&quot;指令和 ngFor &quot;重复&quot; 指令是这类指令中的典范。</p>

<h2 id="toc_28">Template（模板）</h2>

<p>模板是一种html模块，是Angular渲染<a href="#toc_26">视图</a>时，用于支持和Angular<a href="#toc_11">指令</a>继续执行最重要的<a href="#toc_7">组件</a>。</p>

<p>我们用特殊的模板语法编写模板。</p>

<h2 id="toc_23">Template Expression（模板表达式）</h2>

<p>一种 Javascript 风格的表达式，当用在数据绑定时，Angular 会计算表达式的值。需要学习如何编写模板表达式可查阅<a href="https://github.com/gf-rd/blog/issues/18">模板语法章节</a>。</p>

<h2 id="toc_24">Transpile</h2>

<p>一种代码转换的过程，实现将某种 Javascript 系的语言（例如，TypeScript）转化成另一种 Javascript 系的语言（例如，<a href="#toc_12">ES5</a>）。</p>

<h2 id="toc_25" name="toc_25">TypeScript</h2>

<p>是 Javascript 超集，支持大部分<a href="#toc_12">ECMAScript 2015</a>语言功能和未来可能会作为标准的其它功能，例如<a href="#toc_9">Decorators</a>。</p>

<p>TypeScript 值得注意的另一点，就是他的输入校验能提供编译时检测和其它强大的工具支持（例如，智能的自动完成，重构和智能搜索）。很多代码编辑器或者IDE都自带或者通过插件来使用 TypeScript 。</p>

<p>虽然你可以用其它 Javascript 系的语言（如<a href="#toc_12">ES5</a>）来写 Angular 2，不过 TypeScript 是我们首选语言。</p>

<p>Angular 2 本身就是用 TypeScript 写的。</p>

<p>您可以到<a href="http://www.typescriptlang.org/">其他站点</a>学习更多TypeScript的用法。</p>

<h2 id="toc_26" name="toc_26">View（视图）</h2>

<p>视图就是界面的组成部分，用来展示信息以及响应用户的操作，例如：鼠标点击、移动或键盘操作。</p>

<p>Angualr 在一个或多个<a href="#toc_11">指令</a>的控制下渲染视图，特别是<a href="#toc_7">组件</a>指令和关联的<a href="#toc_28">模板</a>。组件扮演者如此重要的角色，以致我们经常觉得，把组件作为视图是很方便的。</p>

<p>视图常常会嵌套其他视图，其他视图也会随着用户的操作而移除或加载，特别是在路由控制的情况下。</p>

<h2 id="toc_27">Zone</h2>

<p>Zones 是一种封装和拦截 javascript 程序异步行为的机制。</p>

<p>浏览器 DOM 和 javascript 的异步行为不是很多，包括 DOM 事件（如点击），promises，和 XHR 异步网络请求</p>

<p>Zones拦截这些活动，让 zone client 使用者有能够在异步活动发生前后作处理。</p>

<p>Angular 把我们的程序跑在 zone 中，通过检查数据改变，然后更新<a href="#toc_8">绑定数据</a>的视图，从而对异步事件作出响应。</p>

<p>观看Brian Ford的<a href="https://www.youtube.com/watch?v=3IqtmUscE_U">视频</a>， 学习更多关于 zones 的内容。</p>

</body>

**Comment by jiayimu** [comment]
token是一个Angular 类型 ( OpaqueToken )。我们很少直接处理    "taken"->应该是token吧。

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的付出与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看
