### ISSUE TITLE
【Angular2开发指南】4、用户输入

### ISSUE THREAD

**Issue by qinghuama320** [gf-rd/blog#27]
> 用户输入会触发DOM事件。在Angular2.0中，EventBinding被用于监听这些事件，并将输入同步到组件或模型中。

当用户点击链接、或按钮，又或按下键盘，这些操作都会触发[DOM事件](https://developer.mozilla.org/en-US/docs/Web/Events)。本章将介绍如何用[Angular Event Binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#event-binding)语法绑定这些事件。

[在线示例](https://angular.io/docs/ts/latest/guide/user-input.html)

### 绑定用户输入事件
我们可以用Angular Event Binding来绑定任何DOM事件。

Angular Event Binding的语法相当简单，只要把一个模板表达式赋值给用括号括起来的DOM事件名称即可。下面是绑定click事件的写法：

`<button (click)="onClickMe()">Click me!</button>`
其中，等号左边的(click)是绑定的目标事件，右边用引号引起来的文本是“[模板表达式](https://angular.io/docs/ts/latest/guide/template-syntax.html#template-expressions)”，模板表达式中是组件对于click事件的响应函数，比如此处的onClickMe。模板表达式是Javascript添加了一些技巧之后形成的集合的子集。

当我们写一个绑定时，必须非常了解模板表达式的执行上下文。在模板表达式中出现的标识符属于特定上下文对象，该对象通常是控制模板的Angular组件。这种机制使得HTML片段中的每个标识符都指向它所属的组件中的确定方法。
```javascript
@Component({
   selector: 'click-me',
   template: `
     <button (click)="onClickMe()">Click me!</button>
     {{clickMessage}}`
 })
 export class ClickMeComponent {
   clickMessage = '';
   onClickMe(){
     this.clickMessage ='You are my hero!';
   }
}
```
本例中，模板中的onClickMe指向组件的onClickMe方法，所以当用户点击按钮时，Angular会调用组件的onClickMe方法。

### 从$event对象获取用户输入
我们可以绑定任意类型的事件。下面我们为一个input框绑定”keyup”事件，并将输入转化后显示到屏幕上。
第一步：监听keyup事件，代码如下
```
template: `
   <input (keyup)="onKey($event)">
   <p>{{values}}</p>
`
```
这段代码中，Angular为$event创建了一个event对象，然后将$event传递给onKey方法，我们需要的用户数据就在这个对象中。
第二步：处理用户输入。
```javascript
export class KeyUpComponent_v1 {
   values='';
   // without strong typing
   onKey(event:any) {
     this.values += event.target.value + ' | ';
   }
}
```
$event对象的结构是由引发它的事件决定的。keyup事件来自DOM节点，所以$event必然也是一个[标准的DOM事件对象](https://developer.mozilla.org/en-US/docs/Web/API/Event)。因此，我们可以从$event.target的value属性上取到用户的输入。

知道了这些，就不难理解当我们把$event传递给组件的onKey方法时所发生的事情。就是在不断地把用户输入追加到组件的valuse属性上，然后再把values回显到屏幕上。下面是输入字符串”abc”，然后再一一退格删除，我们应该在屏幕上看到

```a | ab | abc | ab | a | |```
![](https://angular.io/resources/images/devguide/user-input/keyup1-anim.gif)

> 上面的代码中，我们把$event当成any类型来处理。我们这么做是为了简化代码，而放弃了强类型。更好也最更常用的方法是为$event赋予一个TypeSctipt的强类型。比如这里可以把它当成HTML 的DOM对象，因此我们可以重写代码如下：
```javascript
export class KeyUpComponent_v1 {
   values='';
   // with strong typing
   onKey(event:KeyboardEvent) {
     this.values += (<HTMLInputElement>event.target).value + ' | ';
   }
}
```
但是，当我们把强类型的DOM事件传递给方法时，也会带来一些严重的问题，即我们对模板细节投入更多精力，而破坏松耦合的开发模式。对于这个问题，我们会在本章的“处理用户按键”部分解决之。

### 从本地模板变量获取用户输入
除了上文提到的$event对象，还有另一种不使用$event的方法。Angular2.0有一种叫“[本地模板变量](https://angular.io/docs/ts/latest/guide/template-syntax.html#local-vars)”的语法，这些变量可以使我们直接访问元素。声明模板变量的方法是在标识符前面加上一个“#”字符。下面我们用一个很简单的例子把键盘输入回显到键盘上。
```javascript
@Component({
   selector: 'loop-back',
   template:`
     <input #box (keyup)="0">
     <p>{{box.value}}</p>
   `
 })
 export class LoopbackComponent { }
```
上面的例子中，我们在<input>元素中声明了一个box的本地模板变量，该变量是<input>元素的引用。因此，我们可以通过box取到input元素的值并将它显示到`<p>`标签中。这个例子中，模板是完全自包含的，并没有绑定组件方法，组件也没有做任何事情。下面是演示效果图，在input框里每按下键盘，屏幕上的显示也跟着变化。

![](https://angular.io/resources/images/devguide/user-input/keyup-loop-back-anim.gif)

> #### 注意：除非绑定了事件，否则输入不会引起显示的改变
Angular只更新那些我们在响应中做了处理的绑定（进而是更新屏幕显示）。举个例子，假设我们为keyup事件绑定了一个什么都不做的表达式——数字0——这是我们能想到的最短的表达式了，那么我们将看不到显示变化的效果。这么处理是Angular2.0为了保证您能展开愉快之旅而采取的聪明之举。

本地模板变量有意思的地方在于，它比通过$evnet对象获取文本框信息简单得多。下面我们用本地模板变量来重写之前的”key-up”例子。
```javascript
@Component({
   selector: 'key-up2',
   template: `
     <input #box (keyup)="onKey(box.value)">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v2 {
   values='';
   onKey(value:string) {
     this.values += value + ' | ';
   }
}
```
除了代码看上去简单些外，这种方法的一个特别好的方面是，我们的组件代码不再需要知道$event的知识或者其结构，而是直接从视图层就可以获得数据。

### 键盘事件过滤（使用key.enter）
实际开发中，我们或许只对用户的“回车”键感兴趣，而不是所有按键。在上面几个示例中，我们为keyup事件绑定的方法会监听所有的按键事件。所以我们的第一件事就是过滤按键，比方用$event.keyCode，然后只有当按钮是“回车键”时才更新values属性。

Angular有一套用于键盘事件的特殊语法，可以为我们过滤建事件。比如，通过绑定Angular的keyup.enter伪事件，我们可以只监听“Enter”事件。keyup.enter伪事件使得只有按下“Enter”键，才更新组件的values属性。此外我们还可以把更新的动作放在表达式中，而不是在组件方法中。虽然这是一个值得怀疑的做法，但姑且就当是一次尝试吧。代码和效果图如下：
```javascript
@Component({
   selector: 'key-up3',
   template: `
     <input #box (keyup.enter)="values=box.value">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v3 {
   values='';
}
```
![](https://angular.io/resources/images/devguide/user-input/keyup3-anim.gif)

### blur事件
我们之前的例子都没有传入输入框的当前状态，比如用户把鼠标移动到页面别处并点击。只有当用户在输入框中按下“回车”键时才更新组件的“values”属性，这显然并不合适。为了解决这个问题，我们要为输入框增加监听blur事件的处理。
```javascript
@Component({
   selector: 'key-up4',
   template: `
     <input #box
       (keyup.enter)="values=box.value"
       (blur)="values=box.value">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v4 {
   values='';
}
```
### 将它们放在一起
我们在之前的的章节中学习了如何[展示数据](https://angular.io/docs/ts/latest/guide/displaying-data.html)，本章又学习了事件绑定技术，下面我们就运用这些技术来创建一个微型应用。该应用用来展示一个英雄列表，当用户输入回车、或点击“Add”按钮、或点击页面的其他地方时为列表增加一个新的项。

![](https://angular.io/resources/images/devguide/user-input/little-tour-anim.gif)

下面是应用组件代码。
```javascript
@Component({
   selector: 'little-tour',
   template: `
     <input #newHero
       (keyup.enter)="addHero(newHero.value)"
       (blur)="addHero(newHero.value); newHero.value='' ">
     <button (click)=addHero(newHero.value)>Add</button>
     <ul><li *ngFor="#hero of heroes">{{hero}}</li></ul>
   `
 })
 export class LittleTourComponent {
   heroes=['Windstorm', 'Bombasto', 'Magneta', 'Tornado'];
   addHero(newHero:string) {
     if (newHero) {
       this.heroes.push(newHero);
     }
   }
}
```
我们从中看到所有的东西，鲜有新的东西，仅仅是前面所学知识的重复。借助本例，我们在此回顾下本章的知识点。

#### 模板变量，newHero
模板变量newHero指向<input>元素，我们可以从<input>的任何兄弟或子节点访问newHero，所以当用户点击按钮时，我们不需要通过css选择器定位输入框再取到它的值。

#### 提取输入框的值
我们本可以将newHero传递给组件的addhero()方法，但是这种方法要求addHero通过<input>的DOM元素才能取到值，有点类似于我们在第一个组件KeyupComponent中那种讨厌的做法。因此，这里我们把输入框的值传递给了addHero()，组件对于HTML或DOM可以一无所知，这才是我们喜欢的方式。

#### 别让模板表达式变得复杂
我们给(blur)绑定了两条js语句，其中第一条调用了addHero方法，第二条把一个空字符串赋值给输入框。这么做看起来理由很充分，因为我们必须在把新英雄加入到列表后清空输入框。而组件本身无法做到这一点——因为组件无法访问到输入框（我们传递给组件的是输入框的值，而不是输入库，设计使然）。虽然这种方法（为blur绑定两条语句）有效，但我们必须很警觉这种把js语句嵌入HTML中的作法。模板表达式的功能很强大，我们应该负责任地使用之，像这种把复杂js语句嵌入HTML的作法应该要避免。

那么，是否应该重新考虑如何把输入框的值传递给组件呢？在本书的弟5章[Forms](https://angular.io/docs/ts/latest/guide/forms.html)，我们将介绍一个更好的方法——NgModel。

### 下一步
我们已经掌握了用于响应用户输入或按键的基本原语。由于这些原语功能强大，用它们处理大量的用户输入时显得有些笨拙。因此，当我们需要在数据输入和模型属性之间建立双向绑定时，我们应该在低级别的事件中处理。Angular提供了一种叫NgModel的双向绑定方法，我们将在下一章[5. 表单](https://github.com/gf-rd/blog/issues/24)学习。

**Comment by qinghuama320** [comment]
用户输入会触发DOM事件。在Angular2.0中，EventBinding被用于监听这些事件，并将输入同步到组件或模型中。
当用户点击链接、或按钮，又或按下键盘，这些操作都会触发DOM事件。本章将介绍如何用Angular Event Binding语法绑定这些事件。

在线示例

绑定用户输入事件
我们可以用Angular Event Binding来绑定任何DOM事件。

Angular Event Binding的语法相当简单，只要把一个模板表达式赋值给用括号括起来的DOM事件名称即可。下面是绑定click事件的写法：

<button (click)="onClickMe()">Click me!</button>
其中，等号左边的(click)是绑定的目标事件，右边用引号引起来的文本是“模板表达式”，模板表达式中是组件对于click事件的响应函数，比

如此处的onClickMe。模板表达式是Javascript添加了一些技巧之后形成的集合的子集。

当我们写一个绑定时，必须非常了解模板表达式的执行上下文。在模板表达式中出现的标识符属于特定上下文对象，该对象通常是控制模

板的Angular组件。这种机制使得HTML片段中的每个标识符都指向它所属的组件中的确定方法。

@Component({
   selector: 'click-me',
   template: `
     <button (click)="onClickMe()">Click me!</button>
     {{clickMessage}}`
 })
 export class ClickMeComponent {
   clickMessage = '';
   onClickMe(){
     this.clickMessage ='You are my hero!';
   }
}
本例中，模板中的onClickMe指向组件的onClickMe方法，所以当用户点击按钮时，Angular会调用组件的onClickMe方法。

从$event对象获取用户输入
我们可以绑定任意类型的事件。下面我们为一个input框绑定”keyup”事件，并将输入转化后显示到屏幕上。

第一步：监听keyup事件，代码如下

template: `
   <input (keyup)="onKey($event)">
   <p>{{values}}</p>
`
这段代码中，Angular为$event创建了一个event对象，然后将$event传递给noKey方法，我们需要的用户数据就在这个对象中。
第二步：处理用户输入。

export class KeyUpComponent_v1 {
   values='';
   // without strong typing
   onKey(event:any) {
     this.values += event.target.value + ' | ';
   }
}
$event对象的结构是由引发它的事件决定的。keyup事件来自DOM节点，所以$event必然也是一个标准的DOM事件对象。因此，我们可以从

$event.target的value属性上取到用户的输入。

知道了这些，就不难理解当我们把$event传递给组件的onKey方法时所发生的事情。就是在不断地把用户输入追加到组件的valuse属性上，然

后再把values回显到屏幕上。下面是输入字符串”abc”，然后再一一退格删除，我们应该在屏幕上看到

a | ab | abc | ab | a | |
前端技术研发组 > 【开发指南翻译】4.用户输入（马清华） > keyup1-anim.gif

上面的代码中，我们把$event当成any类型来处理。我们这么做是为了简化代码，而放弃了强类型。更好也最更常用的方法是为$event

赋予一个TypeSctipt的强类型。比如这里可以把它当成HTML 的DOM对象，因此我们可以重写代码如下：

export class KeyUpComponent_v1 {
   values='';
   // with strong typing
   onKey(event:KeyboardEvent) {
     this.values += (<HTMLInputElement>event.target).value + ' | ';
   }
}
但是，当我们把强类型的DOM事件传递给方法时，也会带来一些严重的问题，即我们对模板细节投入更多精力，而破坏松耦合的开发模

式。对于这个问题，我们会在本章的“处理用户按键”部分解决之。

从本地模板变量获取用户输入
除了上文提到的$event对象，还有另一种不使用$evnent的方法。Angular2.0有一种叫“本地模板变量”的语法，这些变量可以使我们直接访问元素。

声明模板变量的方法是在标识符前面加上一个“#”字符。下面我们用一个很简单的例子把键盘输入回显到键盘上。

@Component({
   selector: 'loop-back',
   template:`
     <input #box (keyup)="0">
     <p>{{box.value}}</p>
   `
 })
 export class LoopbackComponent { }
上面的例子中，我们在<input>元素中声明了一个box的本地模板变量，该变量是<input>元素的引用。因此，我们可以通过box取到input元素的值

并将它显示到<p>标签中。这个例子中，模板是完全自包含的，并没有绑定组件方法，组件也没有做任何事情。下面是演示效果图，在input框里

每按下键盘，屏幕上的显示也跟着变化。

前端技术研发组 > 【开发指南翻译】4.用户输入（马清华） > keyup-loop-back-anim.gif

注意：除非绑定了事件，否则输入不会引起显示的改变
Angular只更新那些我们在响应中做了处理的绑定（进而是更新屏幕显示）。举个例子，假设我们为keyup事件绑定了一个什么都不做的

表达式——数字0——这是我们能想到的最短的表达式了，那么我们将看不到显示变化的效果。这么处理是Angular2.0为了保证您能展

开愉快之旅而采取的聪明之举。

本地模板变量有意思的地方在于，它比通过$evnet对象获取文本框信息简单得多。下面我们用本地模板变量来重写之前的”key-up”例子。

@Component({
   selector: 'key-up2',
   template: `
     <input #box (keyup)="onKey(box.value)">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v2 {
   values='';
   onKey(value:string) {
     this.values += value + ' | ';
   }
}
除了代码看上去简单些外，这种方法的一个特别好的方面是，我们的组件代码不再需要知道$event的知识或者其结构，而是直接从视图层就可以

获得数据。

键盘事件过滤（使用key.enter）
实际开发中，我们或许只对用户的“回车”键感兴趣，而不是所有按键。在上面几个示例中，我们为keyup事件绑定的方法会监听所有的按键事件。

所以我们的第一件事就是过滤按键，比方用$event.keyCode，然后只有当按钮是“回车键”时才更新values属性。

Angular有一套用于键盘事件的特殊语法，可以为我们过滤建事件。比如，通过绑定Angular的keyup.enter伪事件，我们可以只监听“Enter”事件。

keyup.enter伪事件使得只有按下“回车”键，才更新组件的values属性。此外我们还可以把更新的动作放在表达式中，而不是在组件方法中。虽然

这是一个值得怀疑的做法，但姑且就当是一次尝试吧。代码和效果图如下：

@Component({
   selector: 'key-up3',
   template: `
     <input #box (keyup.enter)="values=box.value">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v3 {
   values='';
}
前端技术研发组 > 【开发指南翻译】4.用户输入（马清华） > keyup3-anim.gif

blur事件
我们之前的例子都没有传入输入框的当前状态，比如用户把鼠标移动到页面别处并点击。只有当用户在输入框中按下“回车”键时才更新组件的“values”

属性，这显然并不合适。为了解决这个问题，我们要为输入框增加监听blur事件的处理。

@Component({
   selector: 'key-up4',
   template: `
     <input #box
       (keyup.enter)="values=box.value"
       (blur)="values=box.value">
     <p>{{values}}</p>
   `
 })
 export class KeyUpComponent_v4 {
   values='';
}
将它们放在一起
我们在之前的的章节中学习了如何展示数据，本章又学习了事件绑定技术，下面我们就运用这些技术创建来一个微型应用。该应用用来展示一个英雄

列表，并当用户输入回车、或点击“Add”按钮、或点击页面的其他地方时为列表增加一个新的项。

前端技术研发组 > 【开发指南翻译】4.用户输入（马清华） > little-tour-anim.gif

下面是应用组件代码。

@Component({
   selector: 'little-tour',
   template: `
     <input #newHero
       (keyup.enter)="addHero(newHero.value)"
       (blur)="addHero(newHero.value); newHero.value='' ">
     <button (click)=addHero(newHero.value)>Add</button>
     <ul><li *ngFor="#hero of heroes">{{hero}}</li></ul>
   `
 })
 export class LittleTourComponent {
   heroes=['Windstorm', 'Bombasto', 'Magneta', 'Tornado'];
   addHero(newHero:string) {
     if (newHero) {
       this.heroes.push(newHero);
     }
   }
}
我们从中看到所有的东西，鲜有新的东西，仅仅是前面所学知识的重复。借助本例，我们在此回顾下本章的知识点。

模板变量，newHero
模板变量newHero指向<input>元素，我们可以从<input>的任何兄弟或子节点访问newHero，所以当用户点击按钮时，我们不需要通过css选择器定

位输入框再取到它的值。

提取输入框的值
我们本可以将newHero传递给组件的addhero()方法，但是这种方法要求addHero通过<input>的DOM元素才能取到值，有点类似于我们在第一个组件

KeyupComponent中那种讨厌的做法。因此，这里我们把输入框的值传递给了addHero()，组件对于HTML或DOM可以一无所知，这才是我们喜欢的

方式。

别让模板表达式变得复杂
我们给(blur)绑定了两条js语句，其中第一条调用了addHero方法，第二条把一个空字符串赋值给输入框。这么做看起来理由很充分，因为我们必须在

把新英雄加入到列表后清空输入框。而组件本身无法做到这一点——因为组件无法访问到输入框（我们传递给组件的是输入框的值，而不是输入库，

设计使然）。虽然这种方法（为blur绑定两条语句）有效，但我们必须很警觉这种把js语句嵌入HTML中的作法。模板表达式的功能很强大，我们应该

负责任地使用之，像这种把复杂js语句嵌入HTML的作法应该要避免。

那么，是否应该重新考虑如何把输入框的值传递给组件呢？在本书的弟5章Forms，我们将介绍一个更好的方法——NgModel。

源代码
下一步
我们已经掌握了用于响应用户输入或按键的基本原语。由于这些原语功能强大，用它们处理大量的用户输入时显得有些笨拙。因此，当我们需要在数

据输入和模型属性之间建立双向绑定时，我们应该在低级别的事件中处理。Angular提供了一种叫NgModel的双向绑定方法，我们将在下一章学习。

**Comment by flyher** [comment]
@qinghuama320 
我很疑惑，他们的教程中input为什么不带结束的反斜杠，虽然都能正常，

**Comment by ibufu** [comment]
@flyher google style 里推荐自闭的不要带/，我猜应该是为了减小html的大小吧

**Comment by flyher** [comment]
@ibufu 
不过我倒是很习惯自闭，双引号 :) 似乎字符多了很多，

**Comment by ibufu** [comment]
@flyher html里写双引号，js里写单引号，这样比较好~~

**Comment by lightningtgc** [comment]
备注：这是2015年底翻译的成果，感谢大家的贡献与支持。目前官方已提供正式中文版详情可访问www.angular.cn 查看。
更多内容可以留意广发证券前端团队即将出品的Angular 2原创书籍。
再次感谢大家！
